// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 ScriptX
//
// :everframe-gradle-plugin — optional Gradle plugin (Plan 05-08).
//
// Customer opt-in: `plugins { id("dev.everframe") version "1.2.0" }` in their
// application `build.gradle.kts`. The plugin auto-applies a copy of
// `:everframe-core/consumer-rules.pro` (bundled as a resource) to the host
// module's R8 keep set and turns on Compose Compiler's keep-all-composables
// argument so component display names survive minification.
//
// Published as a separate Maven coordinate. The Gradle plugin marker
// `dev.everframe.gradle.plugin` (auto-generated by `java-gradle-plugin`) is
// what consumers reference in their `pluginManagement { plugins { id(...) } }`.

plugins {
    `java-gradle-plugin`
    alias(libs.plugins.kotlin.jvm)
    `maven-publish`
    signing
    id("org.jetbrains.dokka-javadoc")
}

val agpTestKit by configurations.creating

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

val dokkaJavadocJar by tasks.registering(Jar::class) {
    description = "A Javadoc JAR containing generated Dokka API documentation."
    dependsOn(tasks.named("dokkaGeneratePublicationJavadoc"))
    from(tasks.named("dokkaGeneratePublicationJavadoc").map { it.outputs.files })
    archiveClassifier.set("javadoc")
}

// Plan 05-08 — pin Kotlin JVM target to 17 to match `compileJava`. Without this
// kotlin-jvm 2.1 defaults to the host JDK's class-version (21 here) and AGP
// fails the "Inconsistent JVM-target compatibility" check.
kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation(gradleApi())
    compileOnly("com.android.tools.build:gradle:8.7.2")

    testImplementation(gradleTestKit())
    testImplementation(kotlin("test-junit"))
    testImplementation(libs.junit)
    testImplementation("com.android.tools.build:gradle:8.7.2")
    agpTestKit("com.android.tools.build:gradle:8.7.2")
}

// The npx fallback pins the CLI version this repository ships (EverframeCliVersionTest).
val everframeCliVersion = providers.fileContents(layout.projectDirectory.file("../../../cli/package.json")).asText.map { json ->
    Regex("\"version\"\\s*:\\s*\"([^\"]+)\"").find(json)?.groupValues?.get(1) ?: error("packages/cli/package.json has no version")
}
tasks.processResources {
    inputs.property("cliVersion", everframeCliVersion)
    filesMatching("dev/everframe/gradle/cli-version.properties") { expand("cliVersion" to everframeCliVersion.get()) }
}

tasks.pluginUnderTestMetadata {
    pluginClasspath.from(agpTestKit)
}

gradlePlugin {
    plugins {
        register("everframe") {
            id = "dev.everframe"
            displayName = "Everframe Android Gradle plugin"
            description = "Uploads R8 mappings and native symbols after release builds, and applies Everframe consumer-rules.pro and Compose displayName preservation."
            implementationClass = "dev.everframe.gradle.EverframePlugin"
        }
    }
}

// The plugin implementation uses dev.everframe:gradle-plugin:<version>.
// Gradle generates a separate marker at dev.everframe:dev.everframe.gradle.plugin.
// `java-gradle-plugin` auto-creates `pluginMaven` (the library jar) and a marker
// publication for the plugin id. We add Central-required metadata without
// re-creating the publications.
afterEvaluate {
    publishing {
        publications.named<MavenPublication>("pluginMaven") {
            artifactId = "gradle-plugin"
            artifact(dokkaJavadocJar)
        }
        publications.withType<MavenPublication>().configureEach {
            // Pin groupId on every auto-created publication (java-gradle-plugin
            // emits one library + one marker publication per registered plugin).
            groupId = "dev.everframe"
            pom {
                name.set("Everframe Android — everframe-gradle-plugin")
                description.set("Gradle plugin: uploads R8 mappings and native symbols after release builds, and applies Everframe consumer-rules.pro and Compose displayName preservation.")
                url.set("https://github.com/scriptx-com/everframe")
                licenses {
                    license {
                        name.set("MIT")
                        url.set("https://opensource.org/license/mit")
                    }
                }
                developers {
                    developer {
                        id.set("scriptx")
                        name.set("ScriptX")
                        email.set("engineering@scriptx.com")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/scriptx-com/everframe.git")
                    developerConnection.set("scm:git:ssh://git@github.com/scriptx-com/everframe.git")
                    url.set("https://github.com/scriptx-com/everframe")
                }
                issueManagement {
                    system.set("GitHub")
                    url.set("https://github.com/scriptx-com/everframe/issues")
                }
            }
        }
    }
    signing {
        val signingKey = System.getenv("SIGNING_KEY")
            ?: project.findProperty("signing.key")?.toString()
        val signingPassword = System.getenv("SIGNING_PASSWORD")
            ?: project.findProperty("signing.password")?.toString()
        if (signingKey != null && signingPassword != null) {
            useInMemoryPgpKeys(signingKey, signingPassword)
            sign(publishing.publications)
        } else {
            logger.warn("[everframe-gradle-plugin] GPG signing skipped — SIGNING_KEY / SIGNING_PASSWORD not set. Central Portal bundles require signatures.")
        }
    }
}
