# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 ScriptX

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /packages/sdk-android/android
    schedule:
      interval: weekly
  - package-ecosystem: swift
    directory: /packages/sdk-ios
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

