version = 1
SPDX-PackageName = "Everframe SDKs"
SPDX-PackageDownloadLocation = "https://github.com/scriptx-com/everframe"

[[annotations]]
path = ["*.json", "**/*.json", "patches/*.patch"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 ScriptX"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["examples/react-native/assets/field-photo.png", "examples/react-web/public/media/field-loop.mp4", "examples/react-web/public/media/field-loop.webm", "examples/smarttv-tester/platforms/tizen/icon.png", "examples/smarttv-tester/platforms/webos/icon-80.png", "examples/smarttv-tester/platforms/webos/icon-130.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 ScriptX"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**/gradle/wrapper/gradle-wrapper.jar", "**/gradle/wrapper/gradle-wrapper.properties"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2021 the original authors"
SPDX-License-Identifier = "Apache-2.0"
