// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 ScriptX
//
// :traceitx-gradle-plugin — optional Gradle plugin (Plan 05-08).
//
// Customer opt-in: `plugins { id("com.traceitx") version "1.2.0" }` in their
// application `build.gradle.kts`. The plugin auto-applies a copy of
// `:traceitx-core/consumer-rules.pro` (bundled as a resource) to the host
// module's R8 keep set and turns on Compose Compiler's keep-all-composables
// argument so component display names survive minification.
//
// Published as a separate Maven coordinate. The Gradle plugin marker
// `com.traceitx.gradle.plugin` (auto-generated by `java-gradle-plugin`) is
// what consumers reference in their `pluginManagement { plugins { id(...) } }`.

plugins {
    `java-gradle-plugin`
    alias(libs.plugins.kotlin.jvm)
    `maven-publish`
    id("org.jetbrains.dokka-javadoc")
}

val agpTestKit by configurations.creating

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

val dokkaJavadocJar by tasks.registering(Jar::class) {
    description = "A Javadoc JAR containing generated Dokka API documentation."
    dependsOn(tasks.named("dokkaGeneratePublicationJavadoc"))
    from(tasks.named("dokkaGeneratePublicationJavadoc").map { it.outputs.files })
    archiveClassifier.set("javadoc")
}

// Plan 05-08 — pin Kotlin JVM target to 17 to match `compileJava`. Without this
// kotlin-jvm 2.1 defaults to the host JDK's class-version (21 here) and AGP
// fails the "Inconsistent JVM-target compatibility" check.
kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation(gradleApi())
    compileOnly("com.android.tools.build:gradle:8.7.2")

    testImplementation(gradleTestKit())
    testImplementation(kotlin("test-junit"))
    testImplementation(libs.junit)
    testImplementation("com.android.tools.build:gradle:8.7.2")
    agpTestKit("com.android.tools.build:gradle:8.7.2")
}

tasks.pluginUnderTestMetadata {
    pluginClasspath.from(agpTestKit)
}

gradlePlugin {
    plugins {
        register("traceitx") {
            id = "com.traceitx"
            displayName = "TraceItX Android Gradle plugin"
            description = "Auto-applies TraceItX consumer-rules.pro and Compose displayName preservation to host modules."
            implementationClass = "com.traceitx.gradle.TraceItXPlugin"
        }
    }
}

// Plan 05-08 — publish coordinates: com.traceitx:traceitx-gradle-plugin:<version>
// `java-gradle-plugin` auto-creates `pluginMaven` (the library jar) and a marker
// publication for the plugin id. We add the GitHub Packages repo + POM metadata
// without re-creating the publications.
afterEvaluate {
    publishing {
        publications.named<MavenPublication>("pluginMaven") {
            artifact(dokkaJavadocJar)
        }
        publications.withType<MavenPublication>().configureEach {
            // Pin groupId on every auto-created publication (java-gradle-plugin
            // emits one library + one marker publication per registered plugin).
            groupId = "com.traceitx"
            pom {
                name.set("TraceItX Android — traceitx-gradle-plugin")
                description.set("Optional Gradle plugin: applies TraceItX consumer-rules.pro and Compose displayName preservation.")
                url.set("https://github.com/scriptx-com/traceitx-releases")
                licenses {
                    license {
                        name.set("MIT")
                        url.set("https://opensource.org/license/mit")
                    }
                }
            }
        }
        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/scriptx-com/traceitx-releases")
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                        ?: project.findProperty("gpr.user")?.toString()
                    password = System.getenv("GITHUB_TOKEN")
                        ?: project.findProperty("gpr.token")?.toString()
                }
            }
        }
    }
}
