#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 ScriptX
#
# Materialize examples/android-{compose,views}/local.properties from the
# repo-root .env. Idempotent. Mirrors the iOS gen-local-xcconfig.sh pipeline
# so an Android sample run uses TRACEITX_KEY_ANDROID — this probe's own
# dashboard app key — instead of the throwaway dev key in build.gradle.kts.
#
# Output keys:
#   • traceitx.sample.sdkKey  ← TRACEITX_KEY_ANDROID from .env (consumed in
#                                 examples/android-{compose,views}/app/build.gradle.kts
#                                 via project.findProperty("traceitx.sample.sdkKey"))
#
# local.properties is gitignored in both samples.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

SRC_VAR="TRACEITX_KEY_ANDROID"
INGEST_SDK_KEY=""

if [[ ! -f "${ENV_FILE}" ]]; then
    echo "error: ${ENV_FILE} not found. Copy .env.example → .env and set ${SRC_VAR} to the Android app's SDK key." 1>&2
    exit 1
fi

# Extract the value, stripping any inline `# comment` and surrounding
# whitespace (matches dotenv semantics used by the ingest service).
INGEST_SDK_KEY="$(grep -E "^${SRC_VAR}=" "${ENV_FILE}" | tail -1 | cut -d= -f2- | sed -E 's/[[:space:]]+#.*$//; s/^[[:space:]]+//; s/[[:space:]]+$//')"

if [[ ! "${INGEST_SDK_KEY}" =~ ^txx_live_.{32}$ ]]; then
    echo "error: ${SRC_VAR} in ${ENV_FILE} is missing or malformed (need 'txx_live_' + 32-char body = 41 chars)." 1>&2
    echo "       Create an 'Android' app in the dashboard (http://localhost:8787/admin/), generate its SDK key," 1>&2
    echo "       and paste it as ${SRC_VAR}=txx_live_… in the repo-root .env." 1>&2
    exit 1
fi

write_one() {
    local out_file="$1"
    mkdir -p "$(dirname "${out_file}")"
    cat > "${out_file}" <<EOF
# GENERATED BY examples/android-compose/scripts/gen-local-properties.sh
# Source of truth: repo-root .env. Regenerate via 'pnpm gen-android-config'.
# Gitignored — never commit.
traceitx.sample.sdkKey=${INGEST_SDK_KEY}
EOF
    echo "wrote ${out_file}"
}

write_one "${REPO_ROOT}/examples/android-compose/local.properties"
write_one "${REPO_ROOT}/examples/android-views/local.properties"
