#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 ScriptX
#
# PROTO-01 Swift codegen — generates packages/sdk-ios/Sources/EverframeProtocol/Generated.swift
# from packages/protocol/schemas-json/envelope.v1.schema.json via quicktype.
#
# Drift gate: CI runs `pnpm -w codegen && git diff --exit-code packages/sdk-ios/Sources/EverframeProtocol/`.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SCHEMA_PATH="$REPO_ROOT/packages/protocol/schemas-json/envelope.v1.schema.json"
OUT_PATH="$REPO_ROOT/packages/sdk-ios/Sources/EverframeProtocol/Generated.swift"

if [[ ! -f "$SCHEMA_PATH" ]]; then
  echo "schema.json missing at $SCHEMA_PATH; run 'pnpm schema:generate' first" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT_PATH")"

# Plan-locked invocation adjusted for quicktype@23 valid flags.
# See the implementation notes for rationale.
npx --yes quicktype@23 \
  --src-lang schema \
  --src "$SCHEMA_PATH" \
  --lang swift \
  --top-level ReportEnvelope \
  --struct-or-class struct \
  --density dense \
  --access-level public \
  --type-prefix Everframe \
  --out "$OUT_PATH"

# quicktype's --type-prefix covers schema-derived declarations but leaves its
# two open-JSON helper classes unprefixed. They are public generated types too,
# so normalize both their declarations and every reference before adding the
# provenance header.
node --input-type=module - "$OUT_PATH" <<'NODE'
import { readFileSync, writeFileSync } from 'node:fs';

const path = process.argv[2];
let source = readFileSync(path, 'utf8')
  .replace(/\bJSONNull\b/g, 'EverframeJSONNull')
  .replace(/\bJSONAny\b/g, 'EverframeJSONAny');
const formatPattern = /public enum EverframeFormat: String, Codable \{[\s\S]*?\n\}/u;
if (!formatPattern.test(source)) {
  throw new Error('codegen-swift: EverframeFormat block shape changed');
}
source = source.replace(formatPattern, `public enum EverframeFormat: String, Codable {
    case everframeVideoV1 = "everframe-video-v1"
    case everframeVtreeV1 = "everframe-vtree-v1"
    case rrweb = "rrweb"
    case legacyVideoV1 = "traceitx-video-v1"
    case legacyVtreeV1 = "traceitx-vtree-v1"

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        guard let value = EverframeFormat(rawValue: raw) else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Unknown Everframe replay format '\\(raw)'"
            )
        }
        self = value
    }

    public func encode(to encoder: Encoder) throws {
        let encoded: String
        switch self {
        case .legacyVideoV1: encoded = "everframe-video-v1"
        case .legacyVtreeV1: encoded = "everframe-vtree-v1"
        default: encoded = rawValue
        }
        var container = encoder.singleValueContainer()
        try container.encode(encoded)
    }
}`);
writeFileSync(path, source);
NODE

# Prepend the AUTOGENERATED header marker so CI drift detection and humans
# both see provenance at the top of the file.
# REUSE-IgnoreStart
HEADER=$'// SPDX-License-Identifier: MIT\n// SPDX-FileCopyrightText: 2026 ScriptX\n// AUTOGENERATED by packages/protocol/scripts/codegen-swift.sh \xe2\x80\x94 DO NOT EDIT.\n// To regenerate: pnpm -w codegen\n// CI gate: pnpm -w codegen && git diff --exit-code packages/sdk-ios/Sources/EverframeProtocol/\n\n'
# REUSE-IgnoreEnd
BODY="$(cat "$OUT_PATH")"
printf '%s%s\n' "$HEADER" "$BODY" > "$OUT_PATH"
