#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 ScriptX
//
// Build, instrument and sideload the Roku crash lab.
//   node scripts/run-roku.mjs [--no-deploy] [--no-instrument] [--remote-library <https-url>] [--logs]
// Config comes from the repo-root .env (override path with EVERFRAME_ENV_FILE);
// process env wins over the file.
import { spawnSync } from 'node:child_process';
import { cpSync, createWriteStream, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs as nodeParseArgs } from 'node:util';

const EXAMPLE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REPO = path.resolve(EXAMPLE, '../..');
const SDK = path.join(REPO, 'packages/sdk-roku');
const BUILD = path.join(EXAMPLE, '.build');
const ZIP_NAME = 'everframe-crash-lab.zip';

export function parseArgs(argv) {
  const { values } = nodeParseArgs({
    args: argv,
    options: {
      'no-deploy': { type: 'boolean', default: false },
      'no-instrument': { type: 'boolean', default: false },
      'remote-library': { type: 'string' },
      logs: { type: 'boolean', default: false },
    },
  });
  if (values['remote-library'] && !/^https?:\/\//.test(values['remote-library'])) {
    throw new Error('--remote-library must be an http(s) URL');
  }
  return values;
}

export function loadEnv(processEnv = process.env) {
  const file = processEnv.EVERFRAME_ENV_FILE || path.join(REPO, '.env');
  const fromFile = {};
  if (file !== '/dev/null' && existsSync(file)) {
    for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m) fromFile[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  }
  const pick = (k) => (processEnv[k] !== undefined ? processEnv[k] : fromFile[k]) ?? '';
  return {
    key: pick('EVERFRAME_KEY_ROKU'),
    endpoint: pick('EVERFRAME_INGEST_URL'),
    host: pick('ROKU_HOST'),
    password: pick('ROKU_DEV_PASSWORD'),
  };
}

const brsString = (s) => '"' + String(s).replace(/"/g, '""') + '"';

function run(cmd, args, cwd) {
  const r = spawnSync(cmd, args, { cwd, stdio: 'inherit' });
  if (r.error) throw r.error;
  if (r.status !== 0) throw new Error(`${cmd} ${args.join(' ')} exited ${r.status}`);
}

function streamLogs(host) {
  const logFile = path.join(BUILD, 'console.log');
  const out = createWriteStream(logFile, { flags: 'a' });
  const sock = net.connect(8085, host);
  sock.on('data', (d) => {
    process.stdout.write(d);
    out.write(d);
  });
  sock.on('error', (e) => console.error(`[crash-lab] console: ${e.message}`));
  console.log(`[crash-lab] streaming ${host}:8085 -> ${path.relative(EXAMPLE, logFile)} (Ctrl+C to stop)`);
}

export async function main(argv = process.argv.slice(2), processEnv = process.env) {
  const args = parseArgs(argv);
  const env = loadEnv(processEnv);
  if (!env.key) throw new Error('EVERFRAME_KEY_ROKU is not set (root .env or environment)');
  if (!args['no-deploy'] && (!env.host || !env.password)) {
    throw new Error('ROKU_HOST and ROKU_DEV_PASSWORD are required to deploy (or pass --no-deploy)');
  }
  if (/localhost|127\.0\.0\.1/.test(env.endpoint)) {
    console.log(`[crash-lab] WARNING: EVERFRAME_INGEST_URL=${env.endpoint} points at localhost - the TV cannot reach it. Use your machine's LAN IP.`);
  }

  run('pnpm', ['--filter', '@everframe/roku', 'build'], REPO);
  const sdkVersion = JSON.parse(readFileSync(path.join(SDK, 'package.json'), 'utf8')).version;
  const libZip = `everframe-roku-${sdkVersion}.zip`;
  const libraryUri = args['remote-library'] ?? `pkg:/components/${libZip}`;

  rmSync(BUILD, { recursive: true, force: true });
  const src = path.join(BUILD, 'src');
  const out = path.join(BUILD, 'out');
  mkdirSync(BUILD, { recursive: true });
  for (const part of ['manifest', 'source', 'components']) cpSync(path.join(EXAMPLE, part), path.join(src, part), { recursive: true });
  mkdirSync(path.join(src, 'components/generated'), { recursive: true });
  writeFileSync(
    path.join(src, 'components/generated/ef_config.brs'),
    [
      "' Generated by scripts/run-roku.mjs from .env - do not commit.",
      'function EfExample_Config() as object',
      `    return { sdkKey: ${brsString(env.key)}, endpoint: ${brsString(env.endpoint)}, libraryUri: ${brsString(libraryUri)} }`,
      'end function',
      '',
    ].join('\n'),
  );

  const bundle = !args['remote-library'];
  if (args['no-instrument']) {
    cpSync(src, out, { recursive: true });
    if (bundle) cpSync(path.join(SDK, 'dist', libZip), path.join(out, 'components', libZip));
  } else {
    const cli = ['exec', 'everframe-roku', 'instrument', src, '--out', out, '--exclude', 'components/Excluded.brs', '--exclude', 'components/OomTask.brs'];
    if (bundle) cli.push('--bundle-library');
    run('pnpm', cli, EXAMPLE);
  }

  const rokuDeploy = await import('roku-deploy');
  await rokuDeploy.createPackage({ rootDir: out, outDir: BUILD, outFile: ZIP_NAME, retainStagingDir: false });
  console.log(`[crash-lab] packaged ${path.relative(EXAMPLE, path.join(BUILD, ZIP_NAME))} (library: ${libraryUri})`);

  if (args['no-deploy']) return;
  await rokuDeploy.publish({ host: env.host, password: env.password, rootDir: out, outDir: BUILD, outFile: ZIP_NAME });
  console.log(`[crash-lab] sideloaded to ${env.host}`);
  if (args.logs) streamLogs(env.host);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((e) => {
    console.error(`error: ${e.message}`);
    process.exit(1);
  });
}
