// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 ScriptX
//
// PROTO-03 — Relay control-frame schema (source of truth).
//
// This Zod discriminated union is the single source of truth for the relay's
// WebSocket control-frame envelope. JSON Schema is emitted from it via
// `scripts/generate-json-schema.mjs` (Zod 4 native `z.toJSONSchema`), and
// Swift/Kotlin types are then generated by quicktype@23 from that JSON
// Schema (see `scripts/codegen-relay-{swift,kotlin}.sh`). The cycle is
// guarded by `pnpm -w codegen && git diff --exit-code`.
//
// Threat-model T-06.2-03-02 (Info Disclosure): NO `z.any()` / `z.unknown()`
// anywhere in this file. Screenshot bytes ride binary frames per D-05; only
// literal-typed control fields appear here. Enforced by an inline grep gate
// (see Plan 06.2-03 verification).

import { z } from 'zod';

const Base = z.object({ correlation_id: z.string().optional() });

export const PairCreated = Base.extend({
  type: z.literal('pair.created'),
  pair_id: z.string(),
  pair_token: z.string(),
}).meta({ $id: 'PairCreated' });

export const PairBonded = Base.extend({
  type: z.literal('pair.bonded'),
  pair_id: z.string(),
  // device_token / device_token_expires_at are OPTIONAL — server omits them on
  // the TV-side bond notification (the TV doesn't reconnect with a device
  // token; only the phone does, and the phone receives them on its own
  // pair.bonded leg). Marking them required caused strict-decode failures on
  // Android TV / tvOS and the bond event was silently dropped.
  device_token: z.string().optional(),
  device_token_expires_at: z.string().optional(), // ISO timestamp
  // Companion attach (spec 2026-08-07). Both OPTIONAL and both absent on a
  // QR bond — the relay only populates them when the peer arrived through
  // an authenticated dashboard attach.
  //
  // NO user_id: the device has no use for it, and `attribution_token`
  // already carries the user in a form the device cannot forge. Sending a
  // raw id would invite a device to echo an arbitrary one back at ingest.
  // Unknown keys (like user_id) are silently dropped by default Zod behavior.
  companion_user: z
    .object({
      display_name: z.string().min(1).max(120),
      email: z.string().email().optional(),
    })
    .optional(),
  // Opaque HMAC blob minted at bond; the device echoes it on submit as
  // X-TX-Companion-Attribution. Never logged.
  attribution_token: z.string().max(512).optional(),
}).meta({ $id: 'PairBonded' });

export const PairExpired = Base.extend({
  type: z.literal('pair.expired'),
  pair_id: z.string(),
  reason: z.enum(['inactivity', 'tv_disconnect', 'server_shutdown']),
}).meta({ $id: 'PairExpired' });

// Server → TV. Emitted when the phone WS closes (browser tab close, network
// drop, app backgrounded). The pair record is kept alive for the 5-min
// reconnect grace window — if the phone returns with its device_token, the
// server sends a fresh `pair.bonded` and the TV transitions back to Paired.
// If the grace window elapses, the server emits `pair.expired` with
// reason="inactivity". TV-only; phones never receive this.
export const PhoneDisconnected = Base.extend({
  type: z.literal('phone.disconnected'),
  pair_id: z.string(),
}).meta({ $id: 'PhoneDisconnected' });

// ─── Companion attach PIN (spec 2026-08-19) ──────────────────────────────
//
// Server → TV only. Pushed when a dashboard member requests attach to this
// device; the SDK shows `code` on screen and the member types it into the
// dashboard. The code is generated and verified SERVER-side — these frames
// are the only place it ever crosses the wire, and it never appears in any
// dashboard-facing response. `requested_by_name` is the same non-secret
// display name discovery already returns to every project member.
export const AttachChallenge = Base.extend({
  type: z.literal('attach.challenge'),
  code: z.string().length(4),
  ttl_ms: z.number().int().positive(),
  requested_by_name: z.string().min(1).max(120),
}).meta({ $id: 'AttachChallenge' });

// Server → TV. Dismiss the PIN surface: the challenge expired, was redeemed
// ('attached'), burned out its attempts, or was replaced by a newer request
// ('superseded' — also sent when any bond lands while a challenge is live).
export const AttachChallengeCleared = Base.extend({
  type: z.literal('attach.challenge.cleared'),
  reason: z.enum(['expired', 'attached', 'burned', 'superseded']),
}).meta({ $id: 'AttachChallengeCleared' });

// ─── Companion device naming (spec 2026-08-24) ───────────────────────────
//
// Server → TV only. Pushed when a project member renames this device in the
// dashboard (and available for future resolved-name refreshes). `name` is the
// RESOLVED display name — custom rename, host label, or server-composed
// default — never a personal device name (the SDKs deliberately do not send
// one; see the naming spec). The device shows it on its pairing surface and
// attach badge. Old SDKs strict-decode unknown frame types by dropping them,
// so this is additive-safe.
export const CompanionName = Base.extend({
  type: z.literal('companion.name'),
  name: z.string().min(1).max(80),
}).meta({ $id: 'CompanionName' });

export const ReportRequest = Base.extend({
  type: z.literal('report.request'),
  correlation_id: z.string(),
  // Refreshed companion attribution (round-5 fix, spec 2026-08-07 follow-up).
  // OPTIONAL and populated ONLY when the relay forwards this frame for an
  // attached (companion) pair — absent on an ordinary QR-paired pair's
  // report.request, so that frame stays byte-identical to before this field
  // existed. Minted fresh at the moment this frame is forwarded (not once at
  // bond) so a session that stays attached past the 10-minute attribution
  // TTL keeps attributing every report it files, not just its first. See
  // the relay attribution contract.
  attribution_token: z.string().max(512).optional(),
}).meta({ $id: 'ReportRequest' });

export const ReportAssembled = Base.extend({
  type: z.literal('report.assembled'),
  correlation_id: z.string(),
  // Screenshot MIME widened in protocol 0.3.0 to admit `image/webp` (default
  // for new TV SDKs — ~75% byte reduction). Older TVs still ship `image/png`;
  // the phone consumes the Blob via the native MIME, no branching needed.
  // `z.enum(...)` (not `z.union([literal, ...])`) so the JSON Schema emit is
  // `enum: ["image/png", ...]` — what the Swift / Kotlin codegens consume.
  mime: z.enum(['image/png', 'image/webp', 'image/jpeg']),
  size: z.number().int().positive(),
  toggles: z.object({
    logs: z.boolean(),
    network: z.boolean(),
    /** @deprecated UI-tree capture was removed (spec 2026-08-29). Current
     *  producers always send `false`; kept required so a pre-removal TV's
     *  `true` still parses. */
    uiTree: z.boolean(),
    metadata: z.boolean(),
    screenshot: z.literal(true),
  }),
  counts: z.object({
    logs: z.number().int().nonnegative(),
    network: z.number().int().nonnegative(),
    /** @deprecated UI-tree capture was removed (spec 2026-08-29). Current
     *  producers always send `0`. */
    uiTreeNodes: z.number().int().nonnegative(),
    // Optional (protocol 0.3.x additive): honest breadcrumb inventory for
    // the phone's summary line. Absent on older TVs.
    breadcrumbs: z.number().int().nonnegative().optional(),
  }),
  /**
   * @deprecated UI-tree capture was removed (spec 2026-08-29); no current
   * producer sets this. Retained because a PRE-REMOVAL TV still announces it
   * and still sends the SECOND binary frame it promises (gzipped JSON of the
   * captured UITree, immediately after the screenshot). The phone no longer
   * decodes that frame, but it must still know to drain it — see the
   * `await-legacy-tree` phase in ReporterSurface's inbound assembly tracker.
   */
  tree: z
    .object({
      gzippedSize: z.number().int().positive(),
      rawSize: z.number().int().positive(),
      nodeCount: z.number().int().nonnegative(),
    })
    .optional(),
}).meta({ $id: 'ReportAssembled' });

export const ReportDraftUpdate = Base.extend({
  type: z.literal('report.draft.update'),
  correlation_id: z.string(),
  title: z.string().optional(),
  description_partial: z
    .object({
      text: z.string(),
      redactions: z.array(
        z.object({ start: z.number().int(), end: z.number().int() })
      ),
    })
    .optional(),
}).meta({ $id: 'ReportDraftUpdate' });

const AnnotationList = z.array(
  z.discriminatedUnion('kind', [
    z.object({
      kind: z.literal('stroke'),
      points: z.array(z.tuple([z.number(), z.number()])),
      color: z.string(),
      strokeWidth: z.number(),
    }),
    z.object({
      kind: z.literal('arrow'),
      from: z.tuple([z.number(), z.number()]),
      to: z.tuple([z.number(), z.number()]),
      color: z.string(),
      strokeWidth: z.number(),
    }),
    z.object({
      kind: z.literal('blur'),
      rect: z.object({
        x: z.number(),
        y: z.number(),
        w: z.number(),
        h: z.number(),
      }),
    }),
  ])
);

export const ReportSubmit = Base.extend({
  type: z.literal('report.submit'),
  correlation_id: z.string(),
  title: z.string(),
  description: z.object({
    text: z.string(),
    redactions: z.array(
      z.object({ start: z.number().int(), end: z.number().int() })
    ),
  }),
  annotations: AnnotationList,
  includes: z.object({
    logs: z.boolean(),
    network: z.boolean(),
    /** @deprecated UI-tree capture was removed (spec 2026-08-29). Current
     *  phones always send `false`; kept required so a pre-removal phone's
     *  `true` still parses. */
    uiTree: z.boolean(),
    metadata: z.boolean(),
    screenshot: z.literal(true),
  }),
  /**
   * Additional shots beyond the first (spec 2026-07-17 §3). ABSENT on a
   * single-shot submit, so an old TV's frame and a new phone's single-shot
   * frame stay byte-identical — the existing top-level `annotations` and the
   * first binary remain shot #1's, unchanged.
   *
   * Each entry's baked image arrives as a binary frame preceded by its own
   * `shot.binary {shot_id}` marker, in this array's order.
   */
  shots: z
    .array(
      z.object({
        shot_id: z.string().min(1).max(64),
        annotations: AnnotationList,
      }),
    )
    // Capped at THREE, not by taste but by what ingest accepts: the route
    // registers @fastify/multipart with `files: 6` (envelope + 5 attachment
    // slots). A submit already spends the envelope, the primary screenshot and
    // — when the report carries one — the session replay, so three extras is
    // the largest number that always fits. This used to advertise 8, which the
    // server rejected outright: every submission inside the advertised limit
    // failed. Raising the ingest limit instead is a server-side decision about
    // request memory, so the client stays inside what the server promises.
    .max(3)
    .optional(),
}).meta({ $id: 'ReportSubmit' });

export const ReportCompleted = Base.extend({
  type: z.literal('report.completed'),
  correlation_id: z.string(),
  event_id: z.string(),
}).meta({ $id: 'ReportCompleted' });

export const ReportFailed = Base.extend({
  type: z.literal('report.failed'),
  correlation_id: z.string(),
  reason: z.string(),
}).meta({ $id: 'ReportFailed' });

export const ReportRejected = Base.extend({
  type: z.literal('report.rejected'),
  reason: z.enum(['in_flight']),
}).meta({ $id: 'ReportRejected' });

// Phone → TV. Emitted when the reporter SPA user taps Discard (or hits
// the back-button equivalent) AFTER a report.request was sent. The TV
// should transition out of ReportInProgress back to Paired. The
// correlation_id MUST match the in-flight report's id so the TV can
// reject stale cancellations from a previous report cycle. The relay
// blind-forwards this frame from phone to TV.
export const ReportCancelled = Base.extend({
  type: z.literal('report.cancelled'),
  correlation_id: z.string(),
}).meta({ $id: 'ReportCancelled' });

// ─── Live preview (spec 2026-07-17 §3) ───────────────────────────────────
//
// PRIVACY BOUNDARY: these frames are live screen pixels crossing the relay,
// which the phase-06.2 "booleans not blobs" invariant otherwise forbids. The
// relaxation is deliberate and bounded by structure, not by policy: preview
// is phone-INITIATED only (a device never streams unasked), both sides enforce
// a hard time cap, the relay rate-caps and DROPS rather than buffers, and no
// frame is ever persisted server-side.
//
// The device-side "sharing" indicator was REMOVED on 2026-08-13 (spec
// the public behavior contract). It
// was a deliberate product decision, not an oversight: the remaining four
// mitigations are what make the pixel boundary defensible now, and a device
// streaming to an attached dashboard gives no local signal. Do not cite the
// indicator as a mitigation anywhere without re-adding it.
//
// Frame BYTES ride a binary frame immediately after this header, exactly as
// `report.assembled` does — no base64 in the control channel (T-06.2-03-02).

/** Phone → device. Begin streaming preview frames for this report cycle. */
/**
 * Bounded correlation id for the live-preview and multi-shot families.
 *
 * Not cosmetic: the relay HOLDS a `preview.frame` header until its binary
 * arrives, so an unbounded id is retained server memory that an
 * unauthenticated `/relay/tv` peer chooses the size of — send a header with a
 * multi-megabyte id, never send the binary, repeat per connection. Ids are
 * UUID-shaped in every producer, so 128 is far more than enough.
 */
const CorrelationId = z.string().min(1).max(128);

export const PreviewStart = Base.extend({
  type: z.literal('preview.start'),
  correlation_id: CorrelationId,
}).meta({ $id: 'PreviewStart' });

/**
 * Either direction. Phone sends it when the add-shot screen closes; the
 * device sends it when IT stopped on its own (the 2-minute cap, or a capture
 * source that went away) so the phone can drop the viewport rather than sit
 * on a frozen last frame.
 */
export const PreviewStop = Base.extend({
  type: z.literal('preview.stop'),
  correlation_id: CorrelationId,
  reason: z.enum(['user', 'time_cap', 'capture_unavailable']),
}).meta({ $id: 'PreviewStop' });

/**
 * Device → phone, followed immediately by one binary JPEG frame.
 *
 * `seq` is monotonic per preview session. The relay drops frames under its
 * rate cap, so gaps are NORMAL and are not an error — the phone uses `seq`
 * only to discard an out-of-order straggler, never to detect loss.
 */
export const PreviewFrame = Base.extend({
  type: z.literal('preview.frame'),
  correlation_id: CorrelationId,
  seq: z.number().int().nonnegative(),
  mime: z.literal('image/jpeg'),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
}).meta({ $id: 'PreviewFrame' });

// ─── Multi-shot capture (spec 2026-07-17 §3) ─────────────────────────────

/** Normalized 0–1 crop rect in captured-frame space. */
const NormalizedRect = z.object({
  x: z.number().min(0).max(1),
  y: z.number().min(0).max(1),
  w: z.number().min(0).max(1),
  h: z.number().min(0).max(1),
});

/**
 * Phone → device.
 *
 * A `shot_id` the device has NEVER seen means "capture fresh now, at full
 * resolution, and stash it under this id". A KNOWN `shot_id` means "re-crop
 * the existing stash" and must never re-capture — that is what makes the
 * crop pixel-exact against the frame the user actually saw. The phone
 * generates the ids, so the two cases are unambiguous to the device.
 *
 * `rect` absent = full screen.
 */
export const ShotRequest = Base.extend({
  type: z.literal('shot.request'),
  correlation_id: CorrelationId,
  shot_id: z.string().min(1).max(64),
  rect: NormalizedRect.optional(),
}).meta({ $id: 'ShotRequest' });

/** Device → phone, followed immediately by one binary image frame. */
export const ShotAssembled = Base.extend({
  type: z.literal('shot.assembled'),
  correlation_id: CorrelationId,
  shot_id: z.string().min(1).max(64),
  mime: z.enum(['image/png', 'image/webp', 'image/jpeg']),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  size: z.number().int().positive(),
}).meta({ $id: 'ShotAssembled' });

/**
 * Device → phone. Scoped to ONE shot: the draft and its other shots survive.
 * Deliberately NOT `report.failed`, which tears down the whole report.
 */
export const ShotFailed = Base.extend({
  type: z.literal('shot.failed'),
  correlation_id: CorrelationId,
  shot_id: z.string().min(1).max(64),
  reason: z.string().max(200),
}).meta({ $id: 'ShotFailed' });

/**
 * Phone → device, at submit time. Precedes each baked shot image binary so
 * the ordering is explicit rather than positional — the device never has to
 * infer which image belongs to which `shot_id` by counting frames.
 */
export const ShotBinary = Base.extend({
  type: z.literal('shot.binary'),
  correlation_id: CorrelationId,
  shot_id: z.string().min(1).max(64),
}).meta({ $id: 'ShotBinary' });

export const RelayMessage = z
  .discriminatedUnion('type', [
    PairCreated,
    PairBonded,
    PairExpired,
    PhoneDisconnected,
    AttachChallenge,
    AttachChallengeCleared,
    CompanionName,
    ReportRequest,
    ReportAssembled,
    ReportDraftUpdate,
    ReportSubmit,
    ReportCompleted,
    ReportFailed,
    ReportRejected,
    ReportCancelled,
    PreviewStart,
    PreviewStop,
    PreviewFrame,
    ShotRequest,
    ShotAssembled,
    ShotFailed,
    ShotBinary,
  ])
  .meta({ $id: 'RelayMessage' });

export type RelayMessage = z.infer<typeof RelayMessage>;
