#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 ScriptX
#
# Single-source-of-truth version propagation for the iOS SDK.
#
# Reads `spec.version` from Everframe.podspec (the canonical source) and
# regenerates every place that has to reference the version literal:
#
#   * Sources/Everframe/Generated/SDKVersion.swift  — runtime constant read
#                                                    by Everframe.SDK_VERSION
#   * Package.binary.swift                         — `binaryVersion` literal
#                                                    used to build the
#                                                    GitHub Release URL
#
# Intentionally NOT in scope here:
#   * Package.binary.swift checksums — those depend on the rebuilt xcframework
#     zips, so `build-xcframework.sh` writes them (its `sync_binary_checksums`,
#     Release builds only) once the zips exist.
#
# CONSEQUENCE, and the reason `verify-binary-checksums.sh` exists: running
# THIS script alone — the normal way to bump a version — leaves the manifest
# internally inconsistent, pointing `v<new>/` URLs at the previous release's
# checksums. That is expected and harmless on a feature branch; it is fatal if
# it reaches a release, because SwiftPM rejects every consumer fetch. Do not
# "fix" it by hand-writing checksums for artifacts that don't exist yet.
#
# Idempotent: rerunning with no podspec change is a no-op (regenerated files
# are byte-identical, so `git diff` stays clean).
#
# Invoked automatically by `build-xcframework.sh` so the xcframework can
# never go out the door with a stale version. Devs can run it standalone
# after bumping `spec.version` to refresh the committed Swift constant.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
PODSPEC="${PKG_DIR}/Everframe.podspec"
GENERATED_SWIFT="${PKG_DIR}/Sources/Everframe/Generated/SDKVersion.swift"
BINARY_MANIFEST="${PKG_DIR}/Package.binary.swift"

# Extract the podspec version literal. The line looks like:
#   spec.version      = "0.1.1"
# Whitespace between tokens varies — match anything before/after the equals,
# capture the double-quoted string. awk is more robust than sed here because
# BSD sed (macOS default) doesn't grok extended regex the same way as GNU.
VERSION="$(awk -F'"' '/^[[:space:]]*spec\.version[[:space:]]*=/ { print $2; exit }' "${PODSPEC}")"

if [[ -z "${VERSION}" ]]; then
    echo "error: could not parse spec.version from ${PODSPEC}" 1>&2
    exit 1
fi

# Lightweight SemVer sanity check so a typo doesn't propagate downstream.
if ! [[ "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.-]+)?$ ]]; then
    echo "error: '${VERSION}' is not a valid SemVer string" 1>&2
    exit 1
fi

# 1. Regenerate Generated/SDKVersion.swift
mkdir -p "$(dirname "${GENERATED_SWIFT}")"
cat > "${GENERATED_SWIFT}" <<EOF
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 ScriptX
//
// AUTO-GENERATED. DO NOT EDIT BY HAND.
//
// Regenerated by \`packages/sdk-ios/scripts/sync-version.sh\` from
// \`Everframe.podspec\`'s \`spec.version\` line (the single source of truth for
// the iOS SDK version). The sync script is invoked automatically as the
// first step of \`scripts/build-xcframework.sh\`, so the xcframework build
// can never produce a stale value. For in-IDE development this committed
// file is what Xcode + SwiftPM see.
//
// The constant is intentionally module-scoped (not nested in a type) so
// \`Everframe.swift\` can reference it without an extra import. It is \`internal\`
// because consumers should read \`Everframe.SDK_VERSION\` — the wrapped public
// surface, not this implementation detail.
let EverframeSDKVersion: String = "${VERSION}"
EOF

# 2. Patch Package.binary.swift's `binaryVersion` literal. The line looks like:
#       let binaryVersion = "0.1.1"
# Use a tmpfile + mv so the operation is atomic and BSD sed-friendly.
TMP="$(mktemp)"
awk -v v="${VERSION}" '
    /^let binaryVersion =/ { print "let binaryVersion = \"" v "\""; next }
    { print }
' "${BINARY_MANIFEST}" > "${TMP}"
mv "${TMP}" "${BINARY_MANIFEST}"

echo "[sync-version] SDK version = ${VERSION}"
echo "[sync-version] updated: ${GENERATED_SWIFT#${PKG_DIR}/}"
echo "[sync-version] updated: ${BINARY_MANIFEST#${PKG_DIR}/}"
