#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 ScriptX
//
// Projects the TraceItX SDK key from the repo-root `.env` into this Expo
// app's `.env` with the `EXPO_PUBLIC_*` prefix that Expo SDK 56 picks up at
// bundle time. Source of truth is the root file — never edit
// `examples/react-native/.env` directly (it's gitignored and overwritten on
// every `pnpm start`/`ios`/`android`).
//
// Mapping:
//   TRACEITX_KEY_RN → EXPO_PUBLIC_TRACEITX_KEY
//
// Each probe app has its own dashboard app + SDK key. This one reads the
// React Native key; the web/iOS/Android gen scripts read their own vars.
//
// Ingest URL is no longer plumbed through JS — the native iOS/Android SDKs
// bake it at compile time. Override locally by building those SDKs with
// `TRACEITX_DEV_INGEST_URL=…` in the shell environment.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..', '..');
const rootEnvPath = resolve(repoRoot, '.env');
const exampleEnvPath = resolve(__dirname, '..', '.env');

function parseEnv(text) {
  const out = {};
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const k = line.slice(0, eq).trim();
    let v = line.slice(eq + 1).trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1);
    } else {
      // Strip inline `# comment` on unquoted values (dotenv semantics).
      v = v.replace(/\s+#.*$/, '').trim();
    }
    out[k] = v;
  }
  return out;
}

const SRC_VAR = 'TRACEITX_KEY_RN';

if (!existsSync(rootEnvPath)) {
  console.error(`[sync-env] ${rootEnvPath} not found. Copy .env.example → .env and set ${SRC_VAR} to the React Native app's SDK key.`);
  process.exit(1);
}

const env = parseEnv(readFileSync(rootEnvPath, 'utf8'));
const key = env[SRC_VAR] ?? '';

if (!key.startsWith('txx_live_') || key.length !== 41) {
  console.error(
    `[sync-env] ${SRC_VAR} in repo-root .env is missing or not validator-shaped.\n` +
      `           Required: 'txx_live_' prefix (9 chars) + 32-char body = 41 chars total.\n` +
      `           Got: '${key}' (${key.length} chars).\n` +
      `           Create a 'React Native' app in the dashboard (http://localhost:8787/admin/),\n` +
      `           generate its SDK key, and paste it as ${SRC_VAR}=txx_live_… in the repo-root .env.`
  );
  process.exit(1);
}

const body =
  `# Auto-generated by scripts/sync-env.mjs from <repo-root>/.env — DO NOT EDIT.\n` +
  `EXPO_PUBLIC_TRACEITX_KEY=${key}\n`;

writeFileSync(exampleEnvPath, body, 'utf8');
console.log(`[sync-env] wrote ${exampleEnvPath} (key=${key.slice(0, 13)}…)`);
