#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 ScriptX
#
# Materialize examples/ios-native/Config/Local.xcconfig from the repo-root .env.
# Idempotent. Reads TRACEITX_KEY_IOS (this probe's own dashboard app key) and
# hard-fails if it's missing or malformed, rather than baking an empty key that
# would throw .missingAppId at SampleApp launch.
#
# The ingest URL is no longer projected here — the SDK bakes it at compile
# time via #if DEBUG / Release. To override locally for the SDK build itself,
# set TRACEITX_DEV_INGEST_URL in your Xcode scheme env.
set -euo pipefail

# Locate the sample-app directory (examples/ios-native), from which the repo
# root and the output path are both derived.
#
# `$SRCROOT` FIRST, and BASH_SOURCE only as the fallback. Xcode does not execute
# this file in place: it inlines the script's text into a generated
# `Script-<uuid>.sh` under DerivedData and runs THAT, so inside a build phase
# `${BASH_SOURCE[0]}` points at
# …/Build/Intermediates.noindex/…/IntermediateBuildFilesPath/, and
# `${SCRIPT_DIR}/../../..` resolves to a DerivedData ancestor rather than the
# checkout. The script then looked for `.env` inside DerivedData, never found
# it, and — now that a missing file is fatal rather than a warning — failed the
# build outright with a path no one recognises.
#
# The older, permissive version of this script had the identical bug and hid
# it: it warned, continued, and emitted an EMPTY INGEST_SDK_KEY, so the sample
# app built fine and then threw `.missingAppId` at launch. "Build succeeds,
# app dies on start" was the bug; the hard-fail exposed it rather than causing
# it.
#
# Xcode always sets SRCROOT to the .xcodeproj's directory (examples/ios-native),
# which is exactly the anchor needed. Direct CLI runs (`pnpm gen-ios-config`,
# or invoking this file by hand) have no SRCROOT and fall back to the
# file-relative path, which is correct in that context.
if [[ -n "${SRCROOT:-}" ]]; then
    APP_DIR="${SRCROOT}"
else
    APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
REPO_ROOT="$(cd "${APP_DIR}/../.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
OUT_FILE="${APP_DIR}/Config/Local.xcconfig"

SRC_VAR="TRACEITX_KEY_IOS"
INGEST_SDK_KEY=""

if [[ ! -f "${ENV_FILE}" ]]; then
    echo "error: ${ENV_FILE} not found. Copy .env.example → .env and set ${SRC_VAR} to the iOS app's SDK key." 1>&2
    exit 1
fi

# Extract the value, stripping any inline `# comment` and surrounding
# whitespace (matches dotenv semantics used by the ingest service).
INGEST_SDK_KEY="$(grep -E "^${SRC_VAR}=" "${ENV_FILE}" | tail -1 | cut -d= -f2- | sed -E 's/[[:space:]]+#.*$//; s/^[[:space:]]+//; s/[[:space:]]+$//')"

if [[ ! "${INGEST_SDK_KEY}" =~ ^txx_live_.{32}$ ]]; then
    echo "error: ${SRC_VAR} in ${ENV_FILE} is missing or malformed (need 'txx_live_' + 32-char body = 41 chars)." 1>&2
    echo "       Create an 'iOS' app in the dashboard (http://localhost:8787/admin/), generate its SDK key," 1>&2
    echo "       and paste it as ${SRC_VAR}=txx_live_… in the repo-root .env." 1>&2
    exit 1
fi

mkdir -p "$(dirname "${OUT_FILE}")"
cat > "${OUT_FILE}" <<EOF
// GENERATED BY scripts/gen-local-xcconfig.sh — DO NOT EDIT BY HAND.
// Source of truth: repo-root .env. Regenerate via 'pnpm gen-ios-config'.
INGEST_SDK_KEY = ${INGEST_SDK_KEY}
EOF

echo "wrote ${OUT_FILE}"
