#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 ScriptX
# Generated by `everframe setup xcode --print-script`. EVERFRAME_APP_ID supplies the app ID.
set -uo pipefail
if [ "${CONFIGURATION:-}" = "Debug" ] && [ "${EVERFRAME_UPLOAD_DEBUG:-}" != "1" ]; then
  echo "everframe: skipping symbol upload: Debug configuration (set EVERFRAME_UPLOAD_DEBUG=1 to upload Debug symbols)"
  exit 0
fi
EVERFRAME_STRICT=0; case "${EVERFRAME_SYMBOLS_STRICT:-}" in 1|true) EVERFRAME_STRICT=1;; esac
if [ -z "${EVERFRAME_API_TOKEN:-}" ] && [ "$EVERFRAME_STRICT" = 0 ]; then
  echo "warning: everframe: no EVERFRAME_API_TOKEN, skipping symbol upload. Crashes from this build will show raw addresses. Set EVERFRAME_API_TOKEN to a token with the artifacts:write scope, or set EVERFRAME_SYMBOLS_STRICT=1 to fail the build instead."
  exit 0
fi
if [ -f "$SRCROOT/.xcode.env" ]; then . "$SRCROOT/.xcode.env"; fi
if [ -f "$SRCROOT/.xcode.env.local" ]; then . "$SRCROOT/.xcode.env.local"; fi
export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
EVERFRAME_NODE="${NODE_BINARY:-node}"
if [ -z "${EVERFRAME_CLI_JS:-}" ]; then EVERFRAME_CLI_JS="$(cd "$SRCROOT" && "$EVERFRAME_NODE" -p "require.resolve('@everframe/cli')" 2>/dev/null || true)"; fi
EVERFRAME_STATUS=0
if [ -n "$EVERFRAME_CLI_JS" ]; then "$EVERFRAME_NODE" "$EVERFRAME_CLI_JS" dsym upload-build --xcode || EVERFRAME_STATUS=$?; else npx --yes "@everframe/cli@0.1.0" dsym upload-build --xcode || EVERFRAME_STATUS=$?; fi
if [ "$EVERFRAME_STATUS" != 0 ] && [ "$EVERFRAME_STRICT" = 0 ]; then
  echo "warning: everframe: the symbol upload stopped with exit status $EVERFRAME_STATUS. Crashes from this build will show raw addresses until its symbols are uploaded. Set EVERFRAME_SYMBOLS_STRICT=1 to fail the build instead."
  exit 0
fi
exit "$EVERFRAME_STATUS"
