// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 ScriptX
// AUTOGENERATED by packages/protocol/scripts/codegen-swift.sh — DO NOT EDIT.
// To regenerate: pnpm -w codegen
// CI gate: pnpm -w codegen && git diff --exit-code packages/sdk-ios/Sources/EverframeProtocol/

// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse the JSON, add this file to your project and do:
//
//   let everframeReportEnvelope = try EverframeReportEnvelope(json)

import Foundation

// MARK: - EverframeReportEnvelope
public struct EverframeReportEnvelope: Codable {
    public let attachments: [EverframeAttachment]
    public let captureControl: EverframeCaptureControl
    public let captures: EverframeCaptures
    public let context: EverframeContext
    public let payload: EverframePayload
    public let protocolVersion: EverframeProtocolVersion
    public let reporter: EverframeReporter
    public let reportID: String
    public let sdk: EverframeSDK
    public let sessionID: String?
    public let source: EverframeReportEnvelopeSource?
    public let submittedAt: Date

    public enum CodingKeys: String, CodingKey {
        case attachments, captureControl, captures, context, payload, protocolVersion, reporter
        case reportID = "reportId"
        case sdk
        case sessionID = "sessionId"
        case source, submittedAt
    }

    public init(attachments: [EverframeAttachment], captureControl: EverframeCaptureControl, captures: EverframeCaptures, context: EverframeContext, payload: EverframePayload, protocolVersion: EverframeProtocolVersion, reporter: EverframeReporter, reportID: String, sdk: EverframeSDK, sessionID: String?, source: EverframeReportEnvelopeSource?, submittedAt: Date) {
        self.attachments = attachments
        self.captureControl = captureControl
        self.captures = captures
        self.context = context
        self.payload = payload
        self.protocolVersion = protocolVersion
        self.reporter = reporter
        self.reportID = reportID
        self.sdk = sdk
        self.sessionID = sessionID
        self.source = source
        self.submittedAt = submittedAt
    }
}

// MARK: EverframeReportEnvelope convenience initializers and mutators

public extension EverframeReportEnvelope {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeReportEnvelope.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        attachments: [EverframeAttachment]? = nil,
        captureControl: EverframeCaptureControl? = nil,
        captures: EverframeCaptures? = nil,
        context: EverframeContext? = nil,
        payload: EverframePayload? = nil,
        protocolVersion: EverframeProtocolVersion? = nil,
        reporter: EverframeReporter? = nil,
        reportID: String? = nil,
        sdk: EverframeSDK? = nil,
        sessionID: String?? = nil,
        source: EverframeReportEnvelopeSource?? = nil,
        submittedAt: Date? = nil
    ) -> EverframeReportEnvelope {
        return EverframeReportEnvelope(
            attachments: attachments ?? self.attachments,
            captureControl: captureControl ?? self.captureControl,
            captures: captures ?? self.captures,
            context: context ?? self.context,
            payload: payload ?? self.payload,
            protocolVersion: protocolVersion ?? self.protocolVersion,
            reporter: reporter ?? self.reporter,
            reportID: reportID ?? self.reportID,
            sdk: sdk ?? self.sdk,
            sessionID: sessionID ?? self.sessionID,
            source: source ?? self.source,
            submittedAt: submittedAt ?? self.submittedAt
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeAttachment
public struct EverframeAttachment: Codable {
    public let byteLength: Double
    public let contentType: String
    public let durationMS: Double?
    public let format: EverframeFormat?
    public let height: Double?
    public let kind: EverframeAttachmentKind
    public let partName: String
    public let replayStartEpochMS: Double?
    public let sha256: String
    public let width: Double?

    public enum CodingKeys: String, CodingKey {
        case byteLength, contentType
        case durationMS = "durationMs"
        case format, height, kind, partName
        case replayStartEpochMS = "replayStartEpochMs"
        case sha256, width
    }

    public init(byteLength: Double, contentType: String, durationMS: Double?, format: EverframeFormat?, height: Double?, kind: EverframeAttachmentKind, partName: String, replayStartEpochMS: Double?, sha256: String, width: Double?) {
        self.byteLength = byteLength
        self.contentType = contentType
        self.durationMS = durationMS
        self.format = format
        self.height = height
        self.kind = kind
        self.partName = partName
        self.replayStartEpochMS = replayStartEpochMS
        self.sha256 = sha256
        self.width = width
    }
}

// MARK: EverframeAttachment convenience initializers and mutators

public extension EverframeAttachment {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeAttachment.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        byteLength: Double? = nil,
        contentType: String? = nil,
        durationMS: Double?? = nil,
        format: EverframeFormat?? = nil,
        height: Double?? = nil,
        kind: EverframeAttachmentKind? = nil,
        partName: String? = nil,
        replayStartEpochMS: Double?? = nil,
        sha256: String? = nil,
        width: Double?? = nil
    ) -> EverframeAttachment {
        return EverframeAttachment(
            byteLength: byteLength ?? self.byteLength,
            contentType: contentType ?? self.contentType,
            durationMS: durationMS ?? self.durationMS,
            format: format ?? self.format,
            height: height ?? self.height,
            kind: kind ?? self.kind,
            partName: partName ?? self.partName,
            replayStartEpochMS: replayStartEpochMS ?? self.replayStartEpochMS,
            sha256: sha256 ?? self.sha256,
            width: width ?? self.width
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum EverframeFormat: String, Codable {
    case everframeVideoV1 = "everframe-video-v1"
    case everframeVtreeV1 = "everframe-vtree-v1"
    case rrweb = "rrweb"
    case legacyVideoV1 = "traceitx-video-v1"
    case legacyVtreeV1 = "traceitx-vtree-v1"

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        guard let value = EverframeFormat(rawValue: raw) else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Unknown Everframe replay format '\(raw)'"
            )
        }
        self = value
    }

    public func encode(to encoder: Encoder) throws {
        let encoded: String
        switch self {
        case .legacyVideoV1: encoded = "everframe-video-v1"
        case .legacyVtreeV1: encoded = "everframe-vtree-v1"
        default: encoded = rawValue
        }
        var container = encoder.singleValueContainer()
        try container.encode(encoded)
    }
}

public enum EverframeAttachmentKind: String, Codable {
    case annotatedScreenshot = "annotated-screenshot"
    case audio = "audio"
    case other = "other"
    case screenshot = "screenshot"
    case sessionReplay = "session-replay"
    case video = "video"
}

// MARK: - EverframeCaptureControl
public struct EverframeCaptureControl: Codable {
    public let degradedReason: String?
    public let excluded, included: [String]

    public init(degradedReason: String?, excluded: [String], included: [String]) {
        self.degradedReason = degradedReason
        self.excluded = excluded
        self.included = included
    }
}

// MARK: EverframeCaptureControl convenience initializers and mutators

public extension EverframeCaptureControl {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeCaptureControl.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        degradedReason: String?? = nil,
        excluded: [String]? = nil,
        included: [String]? = nil
    ) -> EverframeCaptureControl {
        return EverframeCaptureControl(
            degradedReason: degradedReason ?? self.degradedReason,
            excluded: excluded ?? self.excluded,
            included: included ?? self.included
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeCaptures
public struct EverframeCaptures: Codable {
    public let breadcrumbs: Bool?
    public let focus, logs, network, screenshot: Bool
    public let uiTree: Bool

    public init(breadcrumbs: Bool?, focus: Bool, logs: Bool, network: Bool, screenshot: Bool, uiTree: Bool) {
        self.breadcrumbs = breadcrumbs
        self.focus = focus
        self.logs = logs
        self.network = network
        self.screenshot = screenshot
        self.uiTree = uiTree
    }
}

// MARK: EverframeCaptures convenience initializers and mutators

public extension EverframeCaptures {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeCaptures.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        breadcrumbs: Bool?? = nil,
        focus: Bool? = nil,
        logs: Bool? = nil,
        network: Bool? = nil,
        screenshot: Bool? = nil,
        uiTree: Bool? = nil
    ) -> EverframeCaptures {
        return EverframeCaptures(
            breadcrumbs: breadcrumbs ?? self.breadcrumbs,
            focus: focus ?? self.focus,
            logs: logs ?? self.logs,
            network: network ?? self.network,
            screenshot: screenshot ?? self.screenshot,
            uiTree: uiTree ?? self.uiTree
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeContext
public struct EverframeContext: Codable {
    public let app: EverframeApp
    public let device: EverframeDevice
    public let route: String?

    public init(app: EverframeApp, device: EverframeDevice, route: String?) {
        self.app = app
        self.device = device
        self.route = route
    }
}

// MARK: EverframeContext convenience initializers and mutators

public extension EverframeContext {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeContext.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        app: EverframeApp? = nil,
        device: EverframeDevice? = nil,
        route: String?? = nil
    ) -> EverframeContext {
        return EverframeContext(
            app: app ?? self.app,
            device: device ?? self.device,
            route: route ?? self.route
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeApp
public struct EverframeApp: Codable {
    public let build: String?
    public let name, version: String

    public init(build: String?, name: String, version: String) {
        self.build = build
        self.name = name
        self.version = version
    }
}

// MARK: EverframeApp convenience initializers and mutators

public extension EverframeApp {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeApp.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        build: String?? = nil,
        name: String? = nil,
        version: String? = nil
    ) -> EverframeApp {
        return EverframeApp(
            build: build ?? self.build,
            name: name ?? self.name,
            version: version ?? self.version
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeDevice
public struct EverframeDevice: Codable {
    public let locale: String
    public let model: String?
    public let os, osVersion: String
    public let pixelRatio: Double
    public let screenSize: EverframeScreenSize
    public let timezone: String
    public let userAgent: String?

    public init(locale: String, model: String?, os: String, osVersion: String, pixelRatio: Double, screenSize: EverframeScreenSize, timezone: String, userAgent: String?) {
        self.locale = locale
        self.model = model
        self.os = os
        self.osVersion = osVersion
        self.pixelRatio = pixelRatio
        self.screenSize = screenSize
        self.timezone = timezone
        self.userAgent = userAgent
    }
}

// MARK: EverframeDevice convenience initializers and mutators

public extension EverframeDevice {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeDevice.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        locale: String? = nil,
        model: String?? = nil,
        os: String? = nil,
        osVersion: String? = nil,
        pixelRatio: Double? = nil,
        screenSize: EverframeScreenSize? = nil,
        timezone: String? = nil,
        userAgent: String?? = nil
    ) -> EverframeDevice {
        return EverframeDevice(
            locale: locale ?? self.locale,
            model: model ?? self.model,
            os: os ?? self.os,
            osVersion: osVersion ?? self.osVersion,
            pixelRatio: pixelRatio ?? self.pixelRatio,
            screenSize: screenSize ?? self.screenSize,
            timezone: timezone ?? self.timezone,
            userAgent: userAgent ?? self.userAgent
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeScreenSize
public struct EverframeScreenSize: Codable {
    public let height, width: Double

    public init(height: Double, width: Double) {
        self.height = height
        self.width = width
    }
}

// MARK: EverframeScreenSize convenience initializers and mutators

public extension EverframeScreenSize {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeScreenSize.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        height: Double? = nil,
        width: Double? = nil
    ) -> EverframeScreenSize {
        return EverframeScreenSize(
            height: height ?? self.height,
            width: width ?? self.width
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframePayload
public struct EverframePayload: Codable {
    public let annotations: [EverframeJSONAny]?
    public let breadcrumbs: [EverframeBreadcrumb]?
    public let crash: EverframeCrash?
    public let extra: String?
    public let focus: EverframeFocus?
    public let logs, network: [EverframeJSONAny]?
    public let networkBodies: [EverframeNetworkBody]?
    public let redactions: [EverframeJSONAny]?
    public let resources: [EverframeResource]?
    public let vitals: [EverframeVital]?

    public init(annotations: [EverframeJSONAny]?, breadcrumbs: [EverframeBreadcrumb]?, crash: EverframeCrash?, extra: String?, focus: EverframeFocus?, logs: [EverframeJSONAny]?, network: [EverframeJSONAny]?, networkBodies: [EverframeNetworkBody]?, redactions: [EverframeJSONAny]?, resources: [EverframeResource]?, vitals: [EverframeVital]?) {
        self.annotations = annotations
        self.breadcrumbs = breadcrumbs
        self.crash = crash
        self.extra = extra
        self.focus = focus
        self.logs = logs
        self.network = network
        self.networkBodies = networkBodies
        self.redactions = redactions
        self.resources = resources
        self.vitals = vitals
    }
}

// MARK: EverframePayload convenience initializers and mutators

public extension EverframePayload {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframePayload.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        annotations: [EverframeJSONAny]?? = nil,
        breadcrumbs: [EverframeBreadcrumb]?? = nil,
        crash: EverframeCrash?? = nil,
        extra: String?? = nil,
        focus: EverframeFocus?? = nil,
        logs: [EverframeJSONAny]?? = nil,
        network: [EverframeJSONAny]?? = nil,
        networkBodies: [EverframeNetworkBody]?? = nil,
        redactions: [EverframeJSONAny]?? = nil,
        resources: [EverframeResource]?? = nil,
        vitals: [EverframeVital]?? = nil
    ) -> EverframePayload {
        return EverframePayload(
            annotations: annotations ?? self.annotations,
            breadcrumbs: breadcrumbs ?? self.breadcrumbs,
            crash: crash ?? self.crash,
            extra: extra ?? self.extra,
            focus: focus ?? self.focus,
            logs: logs ?? self.logs,
            network: network ?? self.network,
            networkBodies: networkBodies ?? self.networkBodies,
            redactions: redactions ?? self.redactions,
            resources: resources ?? self.resources,
            vitals: vitals ?? self.vitals
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeBreadcrumb
public struct EverframeBreadcrumb: Codable {
    public let data: [String: EverframeJSONAny]?
    public let kind: EverframeBreadcrumbKind
    public let level: EverframeLevel?
    public let message: String
    public let seq: Int
    public let t: Double
    public let truncated: Bool?

    public init(data: [String: EverframeJSONAny]?, kind: EverframeBreadcrumbKind, level: EverframeLevel?, message: String, seq: Int, t: Double, truncated: Bool?) {
        self.data = data
        self.kind = kind
        self.level = level
        self.message = message
        self.seq = seq
        self.t = t
        self.truncated = truncated
    }
}

// MARK: EverframeBreadcrumb convenience initializers and mutators

public extension EverframeBreadcrumb {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeBreadcrumb.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        data: [String: EverframeJSONAny]?? = nil,
        kind: EverframeBreadcrumbKind? = nil,
        level: EverframeLevel?? = nil,
        message: String? = nil,
        seq: Int? = nil,
        t: Double? = nil,
        truncated: Bool?? = nil
    ) -> EverframeBreadcrumb {
        return EverframeBreadcrumb(
            data: data ?? self.data,
            kind: kind ?? self.kind,
            level: level ?? self.level,
            message: message ?? self.message,
            seq: seq ?? self.seq,
            t: t ?? self.t,
            truncated: truncated ?? self.truncated
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum EverframeBreadcrumbKind: String, Codable {
    case console = "console"
    case custom = "custom"
    case error = "error"
    case lifecycle = "lifecycle"
    case navigation = "navigation"
    case network = "network"
    case tap = "tap"
}

public enum EverframeLevel: String, Codable {
    case debug = "debug"
    case error = "error"
    case info = "info"
    case warn = "warn"
}

// MARK: - EverframeCrash
public struct EverframeCrash: Codable {
    public let causeChain: EverframeCrashCauseChain?
    public let details: EverframeCrashDetails?
    public let exceptionType: String
    public let fatal: Bool?
    public let fingerprint: String
    public let frames: [EverframeFrame]
    public let handled: Bool
    public let jsBundle: EverframeJSBundle?
    public let jvm: EverframeJVMCrashMetadata?
    public let mechanism: String
    public let message: String
    public let occurredAt: Date
    public let threadName: String?

    public init(causeChain: EverframeCrashCauseChain?, details: EverframeCrashDetails?, exceptionType: String, fatal: Bool?, fingerprint: String, frames: [EverframeFrame], handled: Bool, jsBundle: EverframeJSBundle?, jvm: EverframeJVMCrashMetadata?, mechanism: String, message: String, occurredAt: Date, threadName: String?) {
        self.causeChain = causeChain
        self.details = details
        self.exceptionType = exceptionType
        self.fatal = fatal
        self.fingerprint = fingerprint
        self.frames = frames
        self.handled = handled
        self.jsBundle = jsBundle
        self.jvm = jvm
        self.mechanism = mechanism
        self.message = message
        self.occurredAt = occurredAt
        self.threadName = threadName
    }
}

// MARK: EverframeCrash convenience initializers and mutators

public extension EverframeCrash {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeCrash.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        causeChain: EverframeCrashCauseChain?? = nil,
        details: EverframeCrashDetails?? = nil,
        exceptionType: String? = nil,
        fatal: Bool?? = nil,
        fingerprint: String? = nil,
        frames: [EverframeFrame]? = nil,
        handled: Bool? = nil,
        jsBundle: EverframeJSBundle?? = nil,
        jvm: EverframeJVMCrashMetadata?? = nil,
        mechanism: String? = nil,
        message: String? = nil,
        occurredAt: Date? = nil,
        threadName: String?? = nil
    ) -> EverframeCrash {
        return EverframeCrash(
            causeChain: causeChain ?? self.causeChain,
            details: details ?? self.details,
            exceptionType: exceptionType ?? self.exceptionType,
            fatal: fatal ?? self.fatal,
            fingerprint: fingerprint ?? self.fingerprint,
            frames: frames ?? self.frames,
            handled: handled ?? self.handled,
            jsBundle: jsBundle ?? self.jsBundle,
            jvm: jvm ?? self.jvm,
            mechanism: mechanism ?? self.mechanism,
            message: message ?? self.message,
            occurredAt: occurredAt ?? self.occurredAt,
            threadName: threadName ?? self.threadName
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeCrashCauseChain
public struct EverframeCrashCauseChain: Codable {
    public let causes: [EverframeCrashCause]
    public let truncated: Bool

    public init(causes: [EverframeCrashCause], truncated: Bool) {
        self.causes = causes
        self.truncated = truncated
    }
}

// MARK: EverframeCrashCauseChain convenience initializers and mutators

public extension EverframeCrashCauseChain {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeCrashCauseChain.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        causes: [EverframeCrashCause]? = nil,
        truncated: Bool? = nil
    ) -> EverframeCrashCauseChain {
        return EverframeCrashCauseChain(
            causes: causes ?? self.causes,
            truncated: truncated ?? self.truncated
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeCrashCause
public struct EverframeCrashCause: Codable {
    public let exceptionType: String
    public let frames: [EverframeCrashCauseFrame]
    public let framesTruncated: Bool
    public let message: String

    public init(exceptionType: String, frames: [EverframeCrashCauseFrame], framesTruncated: Bool, message: String) {
        self.exceptionType = exceptionType
        self.frames = frames
        self.framesTruncated = framesTruncated
        self.message = message
    }
}

// MARK: EverframeCrashCause convenience initializers and mutators

public extension EverframeCrashCause {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeCrashCause.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        exceptionType: String? = nil,
        frames: [EverframeCrashCauseFrame]? = nil,
        framesTruncated: Bool? = nil,
        message: String? = nil
    ) -> EverframeCrashCause {
        return EverframeCrashCause(
            exceptionType: exceptionType ?? self.exceptionType,
            frames: frames ?? self.frames,
            framesTruncated: framesTruncated ?? self.framesTruncated,
            message: message ?? self.message
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeCrashCauseFrame
public struct EverframeCrashCauseFrame: Codable {
    public let col: Int?
    public let file: String?
    public let function: String?
    public let line: Int?
    public let raw: String

    public init(col: Int?, file: String?, function: String?, line: Int?, raw: String) {
        self.col = col
        self.file = file
        self.function = function
        self.line = line
        self.raw = raw
    }
}

// MARK: EverframeCrashCauseFrame convenience initializers and mutators

public extension EverframeCrashCauseFrame {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeCrashCauseFrame.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        col: Int?? = nil,
        file: String?? = nil,
        function: String?? = nil,
        line: Int?? = nil,
        raw: String? = nil
    ) -> EverframeCrashCauseFrame {
        return EverframeCrashCauseFrame(
            col: col ?? self.col,
            file: file ?? self.file,
            function: function ?? self.function,
            line: line ?? self.line,
            raw: raw ?? self.raw
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeCrashDetails
public struct EverframeCrashDetails: Codable {
    public let context: String?
    public let metadata: [String: EverframeJSONAny]?
    public let severity: EverframeErrorSeverity?
    public let truncated: Bool?

    public init(context: String?, metadata: [String: EverframeJSONAny]?, severity: EverframeErrorSeverity?, truncated: Bool?) {
        self.context = context
        self.metadata = metadata
        self.severity = severity
        self.truncated = truncated
    }
}

// MARK: EverframeCrashDetails convenience initializers and mutators

public extension EverframeCrashDetails {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeCrashDetails.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        context: String?? = nil,
        metadata: [String: EverframeJSONAny]?? = nil,
        severity: EverframeErrorSeverity?? = nil,
        truncated: Bool?? = nil
    ) -> EverframeCrashDetails {
        return EverframeCrashDetails(
            context: context ?? self.context,
            metadata: metadata ?? self.metadata,
            severity: severity ?? self.severity,
            truncated: truncated ?? self.truncated
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum EverframeErrorSeverity: String, Codable {
    case error = "error"
    case info = "info"
    case warning = "warning"
}

// MARK: - EverframeFrame
public struct EverframeFrame: Codable {
    public let col: Int?
    public let file: String?
    public let function: String?
    public let line: Int?
    public let raw: String

    public init(col: Int?, file: String?, function: String?, line: Int?, raw: String) {
        self.col = col
        self.file = file
        self.function = function
        self.line = line
        self.raw = raw
    }
}

// MARK: EverframeFrame convenience initializers and mutators

public extension EverframeFrame {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeFrame.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        col: Int?? = nil,
        file: String?? = nil,
        function: String?? = nil,
        line: Int?? = nil,
        raw: String? = nil
    ) -> EverframeFrame {
        return EverframeFrame(
            col: col ?? self.col,
            file: file ?? self.file,
            function: function ?? self.function,
            line: line ?? self.line,
            raw: raw ?? self.raw
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeJSBundle
public struct EverframeJSBundle: Codable {
    public let buildID: String
    public let bundleName: String
    public let engine: EverframeEngine
    public let platform: EverframeJSBundlePlatform

    public enum CodingKeys: String, CodingKey {
        case buildID = "buildId"
        case bundleName, engine, platform
    }

    public init(buildID: String, bundleName: String, engine: EverframeEngine, platform: EverframeJSBundlePlatform) {
        self.buildID = buildID
        self.bundleName = bundleName
        self.engine = engine
        self.platform = platform
    }
}

// MARK: EverframeJSBundle convenience initializers and mutators

public extension EverframeJSBundle {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeJSBundle.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        buildID: String? = nil,
        bundleName: String? = nil,
        engine: EverframeEngine? = nil,
        platform: EverframeJSBundlePlatform? = nil
    ) -> EverframeJSBundle {
        return EverframeJSBundle(
            buildID: buildID ?? self.buildID,
            bundleName: bundleName ?? self.bundleName,
            engine: engine ?? self.engine,
            platform: platform ?? self.platform
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum EverframeEngine: String, Codable {
    case hermes = "hermes"
}

public enum EverframeJSBundlePlatform: String, Codable {
    case android = "android"
    case ios = "ios"
}

// MARK: - EverframeJVMCrashMetadata
public struct EverframeJVMCrashMetadata: Codable {
    public let causes: [EverframeJVMCause]
    public let causesTruncated: Bool
    public let mappingID: String?

    public enum CodingKeys: String, CodingKey {
        case causes, causesTruncated
        case mappingID = "mappingId"
    }

    public init(causes: [EverframeJVMCause], causesTruncated: Bool, mappingID: String?) {
        self.causes = causes
        self.causesTruncated = causesTruncated
        self.mappingID = mappingID
    }
}

// MARK: EverframeJVMCrashMetadata convenience initializers and mutators

public extension EverframeJVMCrashMetadata {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeJVMCrashMetadata.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        causes: [EverframeJVMCause]? = nil,
        causesTruncated: Bool? = nil,
        mappingID: String?? = nil
    ) -> EverframeJVMCrashMetadata {
        return EverframeJVMCrashMetadata(
            causes: causes ?? self.causes,
            causesTruncated: causesTruncated ?? self.causesTruncated,
            mappingID: mappingID ?? self.mappingID
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeJVMCause
public struct EverframeJVMCause: Codable {
    public let exceptionType: String
    public let frames: [EverframeFrame]
    public let framesTruncated: Bool
    public let message: String

    public init(exceptionType: String, frames: [EverframeFrame], framesTruncated: Bool, message: String) {
        self.exceptionType = exceptionType
        self.frames = frames
        self.framesTruncated = framesTruncated
        self.message = message
    }
}

// MARK: EverframeJVMCause convenience initializers and mutators

public extension EverframeJVMCause {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeJVMCause.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        exceptionType: String? = nil,
        frames: [EverframeFrame]? = nil,
        framesTruncated: Bool? = nil,
        message: String? = nil
    ) -> EverframeJVMCause {
        return EverframeJVMCause(
            exceptionType: exceptionType ?? self.exceptionType,
            frames: frames ?? self.frames,
            framesTruncated: framesTruncated ?? self.framesTruncated,
            message: message ?? self.message
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeFocus
public struct EverframeFocus: Codable {
    public let componentPath: String
    public let cursor: EverframeCursor?
    public let path: [Double]
    public let source: EverframeFocusSource

    public init(componentPath: String, cursor: EverframeCursor?, path: [Double], source: EverframeFocusSource) {
        self.componentPath = componentPath
        self.cursor = cursor
        self.path = path
        self.source = source
    }
}

// MARK: EverframeFocus convenience initializers and mutators

public extension EverframeFocus {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeFocus.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        componentPath: String? = nil,
        cursor: EverframeCursor?? = nil,
        path: [Double]? = nil,
        source: EverframeFocusSource? = nil
    ) -> EverframeFocus {
        return EverframeFocus(
            componentPath: componentPath ?? self.componentPath,
            cursor: cursor ?? self.cursor,
            path: path ?? self.path,
            source: source ?? self.source
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeCursor
public struct EverframeCursor: Codable {
    public let x, y: Double

    public init(x: Double, y: Double) {
        self.x = x
        self.y = y
    }
}

// MARK: EverframeCursor convenience initializers and mutators

public extension EverframeCursor {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeCursor.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        x: Double? = nil,
        y: Double? = nil
    ) -> EverframeCursor {
        return EverframeCursor(
            x: x ?? self.x,
            y: y ?? self.y
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum EverframeFocusSource: String, Codable {
    case keyboard = "keyboard"
    case mouse = "mouse"
    case programmatic = "programmatic"
    case remote = "remote"
    case touch = "touch"
}

// MARK: - EverframeNetworkBody
public struct EverframeNetworkBody: Codable {
    public let ref: Double
    public let reqBody: String?
    public let reqBodyBytes: Double?
    public let reqBodySkipped: EverframeBodySkipped?
    public let reqBodyTruncated: Bool?
    public let reqHeaders: [String: String]?
    public let resBody: String?
    public let resBodyBytes: Double?
    public let resBodySkipped: EverframeBodySkipped?
    public let resBodyTruncated: Bool?
    public let resHeaders: [String: String]?
    public let t: Double

    public init(ref: Double, reqBody: String?, reqBodyBytes: Double?, reqBodySkipped: EverframeBodySkipped?, reqBodyTruncated: Bool?, reqHeaders: [String: String]?, resBody: String?, resBodyBytes: Double?, resBodySkipped: EverframeBodySkipped?, resBodyTruncated: Bool?, resHeaders: [String: String]?, t: Double) {
        self.ref = ref
        self.reqBody = reqBody
        self.reqBodyBytes = reqBodyBytes
        self.reqBodySkipped = reqBodySkipped
        self.reqBodyTruncated = reqBodyTruncated
        self.reqHeaders = reqHeaders
        self.resBody = resBody
        self.resBodyBytes = resBodyBytes
        self.resBodySkipped = resBodySkipped
        self.resBodyTruncated = resBodyTruncated
        self.resHeaders = resHeaders
        self.t = t
    }
}

// MARK: EverframeNetworkBody convenience initializers and mutators

public extension EverframeNetworkBody {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeNetworkBody.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        ref: Double? = nil,
        reqBody: String?? = nil,
        reqBodyBytes: Double?? = nil,
        reqBodySkipped: EverframeBodySkipped?? = nil,
        reqBodyTruncated: Bool?? = nil,
        reqHeaders: [String: String]?? = nil,
        resBody: String?? = nil,
        resBodyBytes: Double?? = nil,
        resBodySkipped: EverframeBodySkipped?? = nil,
        resBodyTruncated: Bool?? = nil,
        resHeaders: [String: String]?? = nil,
        t: Double? = nil
    ) -> EverframeNetworkBody {
        return EverframeNetworkBody(
            ref: ref ?? self.ref,
            reqBody: reqBody ?? self.reqBody,
            reqBodyBytes: reqBodyBytes ?? self.reqBodyBytes,
            reqBodySkipped: reqBodySkipped ?? self.reqBodySkipped,
            reqBodyTruncated: reqBodyTruncated ?? self.reqBodyTruncated,
            reqHeaders: reqHeaders ?? self.reqHeaders,
            resBody: resBody ?? self.resBody,
            resBodyBytes: resBodyBytes ?? self.resBodyBytes,
            resBodySkipped: resBodySkipped ?? self.resBodySkipped,
            resBodyTruncated: resBodyTruncated ?? self.resBodyTruncated,
            resHeaders: resHeaders ?? self.resHeaders,
            t: t ?? self.t
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum EverframeBodySkipped: String, Codable {
    case contentType = "content-type"
    case error = "error"
    case unsupported = "unsupported"
}

// MARK: - EverframeResource
public struct EverframeResource: Codable {
    public let cpu: Double?
    public let extras: [String: Double]?
    public let mem: Double
    public let t: Double

    public init(cpu: Double?, extras: [String: Double]?, mem: Double, t: Double) {
        self.cpu = cpu
        self.extras = extras
        self.mem = mem
        self.t = t
    }
}

// MARK: EverframeResource convenience initializers and mutators

public extension EverframeResource {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeResource.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        cpu: Double?? = nil,
        extras: [String: Double]?? = nil,
        mem: Double? = nil,
        t: Double? = nil
    ) -> EverframeResource {
        return EverframeResource(
            cpu: cpu ?? self.cpu,
            extras: extras ?? self.extras,
            mem: mem ?? self.mem,
            t: t ?? self.t
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeVital
public struct EverframeVital: Codable {
    public let cpu: Double?
    public let extras: [String: Double]?
    public let kind: EverframeVitalKind
    public let mem: Double?
    public let t: Double
    public let data: EverframeJSONAny?
    public let playerID: String?
    public let truncated: Bool?
    public let type: EverframeType?
    public let name: String?

    public enum CodingKeys: String, CodingKey {
        case cpu, extras, kind, mem, t, data
        case playerID = "playerId"
        case truncated, type, name
    }

    public init(cpu: Double?, extras: [String: Double]?, kind: EverframeVitalKind, mem: Double?, t: Double, data: EverframeJSONAny?, playerID: String?, truncated: Bool?, type: EverframeType?, name: String?) {
        self.cpu = cpu
        self.extras = extras
        self.kind = kind
        self.mem = mem
        self.t = t
        self.data = data
        self.playerID = playerID
        self.truncated = truncated
        self.type = type
        self.name = name
    }
}

// MARK: EverframeVital convenience initializers and mutators

public extension EverframeVital {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeVital.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        cpu: Double?? = nil,
        extras: [String: Double]?? = nil,
        kind: EverframeVitalKind? = nil,
        mem: Double?? = nil,
        t: Double? = nil,
        data: EverframeJSONAny?? = nil,
        playerID: String?? = nil,
        truncated: Bool?? = nil,
        type: EverframeType?? = nil,
        name: String?? = nil
    ) -> EverframeVital {
        return EverframeVital(
            cpu: cpu ?? self.cpu,
            extras: extras ?? self.extras,
            kind: kind ?? self.kind,
            mem: mem ?? self.mem,
            t: t ?? self.t,
            data: data ?? self.data,
            playerID: playerID ?? self.playerID,
            truncated: truncated ?? self.truncated,
            type: type ?? self.type,
            name: name ?? self.name
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum EverframeVitalKind: String, Codable {
    case custom = "custom"
    case player = "player"
    case sample = "sample"
}

public enum EverframeType: String, Codable {
    case bitrateChange = "bitrate_change"
    case bufferEnd = "buffer_end"
    case bufferStart = "buffer_start"
    case drm = "drm"
    case droppedFrames = "dropped_frames"
    case error = "error"
    case pause = "pause"
    case play = "play"
    case playerAttach = "player_attach"
    case playerDetach = "player_detach"
    case qualityChange = "quality_change"
    case rateChange = "rate_change"
    case seek = "seek"
    case sourceChange = "source_change"
    case startup = "startup"
    case stats = "stats"
}

public enum EverframeProtocolVersion: String, Codable {
    case the10 = "1.0"
}

// MARK: - EverframeReporter
public struct EverframeReporter: Codable {
    public let description: String
    public let title: String
    public let user: EverframeUser?

    public init(description: String, title: String, user: EverframeUser?) {
        self.description = description
        self.title = title
        self.user = user
    }
}

// MARK: EverframeReporter convenience initializers and mutators

public extension EverframeReporter {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeReporter.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        description: String? = nil,
        title: String? = nil,
        user: EverframeUser?? = nil
    ) -> EverframeReporter {
        return EverframeReporter(
            description: description ?? self.description,
            title: title ?? self.title,
            user: user ?? self.user
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeUser
public struct EverframeUser: Codable {
    public let displayName, email, id: String?

    public init(displayName: String?, email: String?, id: String?) {
        self.displayName = displayName
        self.email = email
        self.id = id
    }
}

// MARK: EverframeUser convenience initializers and mutators

public extension EverframeUser {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeUser.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        displayName: String?? = nil,
        email: String?? = nil,
        id: String?? = nil
    ) -> EverframeUser {
        return EverframeUser(
            displayName: displayName ?? self.displayName,
            email: email ?? self.email,
            id: id ?? self.id
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - EverframeSDK
public struct EverframeSDK: Codable {
    public let formFactor: EverframeFormFactor
    public let name: EverframeName
    /// All TV form factors enumerated from v1 (PLAT-04)
    public let platform: EverframePlatform
    public let version: String

    public init(formFactor: EverframeFormFactor, name: EverframeName, platform: EverframePlatform, version: String) {
        self.formFactor = formFactor
        self.name = name
        self.platform = platform
        self.version = version
    }
}

// MARK: EverframeSDK convenience initializers and mutators

public extension EverframeSDK {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(EverframeSDK.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        formFactor: EverframeFormFactor? = nil,
        name: EverframeName? = nil,
        platform: EverframePlatform? = nil,
        version: String? = nil
    ) -> EverframeSDK {
        return EverframeSDK(
            formFactor: formFactor ?? self.formFactor,
            name: name ?? self.name,
            platform: platform ?? self.platform,
            version: version ?? self.version
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum EverframeFormFactor: String, Codable {
    case desktop = "desktop"
    case phone = "phone"
    case tablet = "tablet"
    case tv = "tv"
}

public enum EverframeName: String, Codable {
    case everframeAndroid = "everframe-android"
    case everframeIos = "everframe-ios"
    case everframeReact = "everframe-react"
    case everframeReactNative = "everframe-react-native"
    case everframeWeb = "everframe-web"
}

/// All TV form factors enumerated from v1 (PLAT-04)
public enum EverframePlatform: String, Codable {
    case android = "android"
    case androidtv = "androidtv"
    case ios = "ios"
    case tizen = "tizen"
    case tvos = "tvos"
    case web = "web"
    case webos = "webos"
}

public enum EverframeReportEnvelopeSource: String, Codable {
    case crash = "crash"
    case error = "error"
    case manual = "manual"
}

// MARK: - Helper functions for creating encoders and decoders

func newJSONDecoder() -> JSONDecoder {
    let decoder = JSONDecoder()
    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
        decoder.dateDecodingStrategy = .iso8601
    }
    return decoder
}

func newJSONEncoder() -> JSONEncoder {
    let encoder = JSONEncoder()
    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
        encoder.dateEncodingStrategy = .iso8601
    }
    return encoder
}

// MARK: - Encode/decode helpers

public class EverframeJSONNull: Codable, Hashable {

    public static func == (lhs: EverframeJSONNull, rhs: EverframeJSONNull) -> Bool {
            return true
    }

    public var hashValue: Int {
            return 0
    }

    public init() {}

    public required init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if !container.decodeNil() {
                    throw DecodingError.typeMismatch(EverframeJSONNull.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for EverframeJSONNull"))
            }
    }

    public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encodeNil()
    }
}

class JSONCodingKey: CodingKey {
    let key: String

    required init?(intValue: Int) {
            return nil
    }

    required init?(stringValue: String) {
            key = stringValue
    }

    var intValue: Int? {
            return nil
    }

    var stringValue: String {
            return key
    }
}

public class EverframeJSONAny: Codable {

    public let value: Any

    static func decodingError(forCodingPath codingPath: [CodingKey]) -> DecodingError {
            let context = DecodingError.Context(codingPath: codingPath, debugDescription: "Cannot decode EverframeJSONAny")
            return DecodingError.typeMismatch(EverframeJSONAny.self, context)
    }

    static func encodingError(forValue value: Any, codingPath: [CodingKey]) -> EncodingError {
            let context = EncodingError.Context(codingPath: codingPath, debugDescription: "Cannot encode EverframeJSONAny")
            return EncodingError.invalidValue(value, context)
    }

    static func decode(from container: SingleValueDecodingContainer) throws -> Any {
            if let value = try? container.decode(Bool.self) {
                    return value
            }
            if let value = try? container.decode(Int64.self) {
                    return value
            }
            if let value = try? container.decode(Double.self) {
                    return value
            }
            if let value = try? container.decode(String.self) {
                    return value
            }
            if container.decodeNil() {
                    return EverframeJSONNull()
            }
            throw decodingError(forCodingPath: container.codingPath)
    }

    static func decode(from container: inout UnkeyedDecodingContainer) throws -> Any {
            if let value = try? container.decode(Bool.self) {
                    return value
            }
            if let value = try? container.decode(Int64.self) {
                    return value
            }
            if let value = try? container.decode(Double.self) {
                    return value
            }
            if let value = try? container.decode(String.self) {
                    return value
            }
            if let value = try? container.decodeNil() {
                    if value {
                            return EverframeJSONNull()
                    }
            }
            if var container = try? container.nestedUnkeyedContainer() {
                    return try decodeArray(from: &container)
            }
            if var container = try? container.nestedContainer(keyedBy: JSONCodingKey.self) {
                    return try decodeDictionary(from: &container)
            }
            throw decodingError(forCodingPath: container.codingPath)
    }

    static func decode(from container: inout KeyedDecodingContainer<JSONCodingKey>, forKey key: JSONCodingKey) throws -> Any {
            if let value = try? container.decode(Bool.self, forKey: key) {
                    return value
            }
            if let value = try? container.decode(Int64.self, forKey: key) {
                    return value
            }
            if let value = try? container.decode(Double.self, forKey: key) {
                    return value
            }
            if let value = try? container.decode(String.self, forKey: key) {
                    return value
            }
            if let value = try? container.decodeNil(forKey: key) {
                    if value {
                            return EverframeJSONNull()
                    }
            }
            if var container = try? container.nestedUnkeyedContainer(forKey: key) {
                    return try decodeArray(from: &container)
            }
            if var container = try? container.nestedContainer(keyedBy: JSONCodingKey.self, forKey: key) {
                    return try decodeDictionary(from: &container)
            }
            throw decodingError(forCodingPath: container.codingPath)
    }

    static func decodeArray(from container: inout UnkeyedDecodingContainer) throws -> [Any] {
            var arr: [Any] = []
            while !container.isAtEnd {
                    let value = try decode(from: &container)
                    arr.append(value)
            }
            return arr
    }

    static func decodeDictionary(from container: inout KeyedDecodingContainer<JSONCodingKey>) throws -> [String: Any] {
            var dict = [String: Any]()
            for key in container.allKeys {
                    let value = try decode(from: &container, forKey: key)
                    dict[key.stringValue] = value
            }
            return dict
    }

    static func encode(to container: inout UnkeyedEncodingContainer, array: [Any]) throws {
            for value in array {
                    if let value = value as? Bool {
                            try container.encode(value)
                    } else if let value = value as? Int64 {
                            try container.encode(value)
                    } else if let value = value as? Double {
                            try container.encode(value)
                    } else if let value = value as? String {
                            try container.encode(value)
                    } else if value is EverframeJSONNull {
                            try container.encodeNil()
                    } else if let value = value as? [Any] {
                            var container = container.nestedUnkeyedContainer()
                            try encode(to: &container, array: value)
                    } else if let value = value as? [String: Any] {
                            var container = container.nestedContainer(keyedBy: JSONCodingKey.self)
                            try encode(to: &container, dictionary: value)
                    } else {
                            throw encodingError(forValue: value, codingPath: container.codingPath)
                    }
            }
    }

    static func encode(to container: inout KeyedEncodingContainer<JSONCodingKey>, dictionary: [String: Any]) throws {
            for (key, value) in dictionary {
                    let key = JSONCodingKey(stringValue: key)!
                    if let value = value as? Bool {
                            try container.encode(value, forKey: key)
                    } else if let value = value as? Int64 {
                            try container.encode(value, forKey: key)
                    } else if let value = value as? Double {
                            try container.encode(value, forKey: key)
                    } else if let value = value as? String {
                            try container.encode(value, forKey: key)
                    } else if value is EverframeJSONNull {
                            try container.encodeNil(forKey: key)
                    } else if let value = value as? [Any] {
                            var container = container.nestedUnkeyedContainer(forKey: key)
                            try encode(to: &container, array: value)
                    } else if let value = value as? [String: Any] {
                            var container = container.nestedContainer(keyedBy: JSONCodingKey.self, forKey: key)
                            try encode(to: &container, dictionary: value)
                    } else {
                            throw encodingError(forValue: value, codingPath: container.codingPath)
                    }
            }
    }

    static func encode(to container: inout SingleValueEncodingContainer, value: Any) throws {
            if let value = value as? Bool {
                    try container.encode(value)
            } else if let value = value as? Int64 {
                    try container.encode(value)
            } else if let value = value as? Double {
                    try container.encode(value)
            } else if let value = value as? String {
                    try container.encode(value)
            } else if value is EverframeJSONNull {
                    try container.encodeNil()
            } else {
                    throw encodingError(forValue: value, codingPath: container.codingPath)
            }
    }

    public required init(from decoder: Decoder) throws {
            if var arrayContainer = try? decoder.unkeyedContainer() {
                    self.value = try EverframeJSONAny.decodeArray(from: &arrayContainer)
            } else if var container = try? decoder.container(keyedBy: JSONCodingKey.self) {
                    self.value = try EverframeJSONAny.decodeDictionary(from: &container)
            } else {
                    let container = try decoder.singleValueContainer()
                    self.value = try EverframeJSONAny.decode(from: container)
            }
    }

    public func encode(to encoder: Encoder) throws {
            if let arr = self.value as? [Any] {
                    var container = encoder.unkeyedContainer()
                    try EverframeJSONAny.encode(to: &container, array: arr)
            } else if let dict = self.value as? [String: Any] {
                    var container = encoder.container(keyedBy: JSONCodingKey.self)
                    try EverframeJSONAny.encode(to: &container, dictionary: dict)
            } else {
                    var container = encoder.singleValueContainer()
                    try EverframeJSONAny.encode(to: &container, value: self.value)
            }
    }
}
