// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 ScriptX
// AUTOGENERATED by packages/protocol/scripts/codegen-relay-swift.mjs — DO NOT EDIT.
// To regenerate: pnpm -w codegen
// CI gate: pnpm -w codegen && git diff --exit-code packages/sdk-ios/Sources/EverframeProtocol/
//
// Custom emitter (not quicktype): quicktype@23 flattens oneOf-with-const into
// a single struct, which violates the SPEC requirement for an enum with
// associated values. See header of codegen-relay-swift.mjs for details.

import Foundation

public struct EverframeAttachChallenge: Codable, Equatable {
    public let code: String
    public let correlationId: String?
    public let requestedByName: String
    public let ttlMs: Int
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case code
        case correlationId = "correlation_id"
        case requestedByName = "requested_by_name"
        case ttlMs = "ttl_ms"
        case type
    }

    public init(code: String, correlationId: String? = nil, requestedByName: String, ttlMs: Int, type: String) {
        self.code = code
        self.correlationId = correlationId
        self.requestedByName = requestedByName
        self.ttlMs = ttlMs
        self.type = type
    }
}

public struct EverframeAttachChallengeCleared: Codable, Equatable {
    public let correlationId: String?
    public let reason: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case reason
        case type
    }

    public init(correlationId: String? = nil, reason: String, type: String) {
        self.correlationId = correlationId
        self.reason = reason
        self.type = type
    }
}

public struct EverframeCompanionName: Codable, Equatable {
    public let correlationId: String?
    public let name: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case name
        case type
    }

    public init(correlationId: String? = nil, name: String, type: String) {
        self.correlationId = correlationId
        self.name = name
        self.type = type
    }
}

public struct EverframePairBonded: Codable, Equatable {
    public let attributionToken: String?
    public let companionUser: EverframePairBondedCompanionUser?
    public let correlationId: String?
    public let deviceToken: String?
    public let deviceTokenExpiresAt: String?
    public let pairId: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case attributionToken = "attribution_token"
        case companionUser = "companion_user"
        case correlationId = "correlation_id"
        case deviceToken = "device_token"
        case deviceTokenExpiresAt = "device_token_expires_at"
        case pairId = "pair_id"
        case type
    }

    public init(attributionToken: String? = nil, companionUser: EverframePairBondedCompanionUser? = nil, correlationId: String? = nil, deviceToken: String? = nil, deviceTokenExpiresAt: String? = nil, pairId: String, type: String) {
        self.attributionToken = attributionToken
        self.companionUser = companionUser
        self.correlationId = correlationId
        self.deviceToken = deviceToken
        self.deviceTokenExpiresAt = deviceTokenExpiresAt
        self.pairId = pairId
        self.type = type
    }
}

public struct EverframePairBondedCompanionUser: Codable, Equatable {
    public let displayName: String
    public let email: String?

    public enum CodingKeys: String, CodingKey {
        case displayName = "display_name"
        case email
    }

    public init(displayName: String, email: String? = nil) {
        self.displayName = displayName
        self.email = email
    }
}

public struct EverframePairCreated: Codable, Equatable {
    public let correlationId: String?
    public let pairId: String
    public let pairToken: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case pairId = "pair_id"
        case pairToken = "pair_token"
        case type
    }

    public init(correlationId: String? = nil, pairId: String, pairToken: String, type: String) {
        self.correlationId = correlationId
        self.pairId = pairId
        self.pairToken = pairToken
        self.type = type
    }
}

public struct EverframePairExpired: Codable, Equatable {
    public let correlationId: String?
    public let pairId: String
    public let reason: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case pairId = "pair_id"
        case reason
        case type
    }

    public init(correlationId: String? = nil, pairId: String, reason: String, type: String) {
        self.correlationId = correlationId
        self.pairId = pairId
        self.reason = reason
        self.type = type
    }
}

public struct EverframePhoneDisconnected: Codable, Equatable {
    public let correlationId: String?
    public let pairId: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case pairId = "pair_id"
        case type
    }

    public init(correlationId: String? = nil, pairId: String, type: String) {
        self.correlationId = correlationId
        self.pairId = pairId
        self.type = type
    }
}

public struct EverframePreviewFrame: Codable, Equatable {
    public let correlationId: String
    public let height: Int
    public let mime: String
    public let seq: Int
    public let type: String
    public let width: Int

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case height
        case mime
        case seq
        case type
        case width
    }

    public init(correlationId: String, height: Int, mime: String, seq: Int, type: String, width: Int) {
        self.correlationId = correlationId
        self.height = height
        self.mime = mime
        self.seq = seq
        self.type = type
        self.width = width
    }
}

public struct EverframePreviewStart: Codable, Equatable {
    public let correlationId: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case type
    }

    public init(correlationId: String, type: String) {
        self.correlationId = correlationId
        self.type = type
    }
}

public struct EverframePreviewStop: Codable, Equatable {
    public let correlationId: String
    public let reason: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case reason
        case type
    }

    public init(correlationId: String, reason: String, type: String) {
        self.correlationId = correlationId
        self.reason = reason
        self.type = type
    }
}

public struct EverframeReportAssembled: Codable, Equatable {
    public let correlationId: String
    public let counts: EverframeReportAssembledCounts
    public let mime: String
    public let size: Int
    public let toggles: EverframeReportAssembledToggles
    public let tree: EverframeReportAssembledTree?
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case counts
        case mime
        case size
        case toggles
        case tree
        case type
    }

    public init(correlationId: String, counts: EverframeReportAssembledCounts, mime: String, size: Int, toggles: EverframeReportAssembledToggles, tree: EverframeReportAssembledTree? = nil, type: String) {
        self.correlationId = correlationId
        self.counts = counts
        self.mime = mime
        self.size = size
        self.toggles = toggles
        self.tree = tree
        self.type = type
    }
}

public struct EverframeReportAssembledCounts: Codable, Equatable {
    public let breadcrumbs: Int?
    public let logs: Int
    public let network: Int
    public let uiTreeNodes: Int

    public enum CodingKeys: String, CodingKey {
        case breadcrumbs
        case logs
        case network
        case uiTreeNodes
    }

    public init(breadcrumbs: Int? = nil, logs: Int, network: Int, uiTreeNodes: Int) {
        self.breadcrumbs = breadcrumbs
        self.logs = logs
        self.network = network
        self.uiTreeNodes = uiTreeNodes
    }
}

public struct EverframeReportAssembledToggles: Codable, Equatable {
    public let logs: Bool
    public let metadata: Bool
    public let network: Bool
    public let screenshot: Bool
    public let uiTree: Bool

    public enum CodingKeys: String, CodingKey {
        case logs
        case metadata
        case network
        case screenshot
        case uiTree
    }

    public init(logs: Bool, metadata: Bool, network: Bool, screenshot: Bool, uiTree: Bool) {
        self.logs = logs
        self.metadata = metadata
        self.network = network
        self.screenshot = screenshot
        self.uiTree = uiTree
    }
}

public struct EverframeReportAssembledTree: Codable, Equatable {
    public let gzippedSize: Int
    public let nodeCount: Int
    public let rawSize: Int

    public enum CodingKeys: String, CodingKey {
        case gzippedSize
        case nodeCount
        case rawSize
    }

    public init(gzippedSize: Int, nodeCount: Int, rawSize: Int) {
        self.gzippedSize = gzippedSize
        self.nodeCount = nodeCount
        self.rawSize = rawSize
    }
}

public struct EverframeReportCancelled: Codable, Equatable {
    public let correlationId: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case type
    }

    public init(correlationId: String, type: String) {
        self.correlationId = correlationId
        self.type = type
    }
}

public struct EverframeReportCompleted: Codable, Equatable {
    public let correlationId: String
    public let eventId: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case eventId = "event_id"
        case type
    }

    public init(correlationId: String, eventId: String, type: String) {
        self.correlationId = correlationId
        self.eventId = eventId
        self.type = type
    }
}

public struct EverframeReportDraftUpdate: Codable, Equatable {
    public let correlationId: String
    public let descriptionPartial: EverframeReportDraftUpdateDescriptionPartial?
    public let title: String?
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case descriptionPartial = "description_partial"
        case title
        case type
    }

    public init(correlationId: String, descriptionPartial: EverframeReportDraftUpdateDescriptionPartial? = nil, title: String? = nil, type: String) {
        self.correlationId = correlationId
        self.descriptionPartial = descriptionPartial
        self.title = title
        self.type = type
    }
}

public struct EverframeReportDraftUpdateDescriptionPartial: Codable, Equatable {
    public let redactions: [EverframeReportDraftUpdateDescriptionPartialRedaction]
    public let text: String

    public enum CodingKeys: String, CodingKey {
        case redactions
        case text
    }

    public init(redactions: [EverframeReportDraftUpdateDescriptionPartialRedaction], text: String) {
        self.redactions = redactions
        self.text = text
    }
}

public struct EverframeReportDraftUpdateDescriptionPartialRedaction: Codable, Equatable {
    public let end: Int
    public let start: Int

    public enum CodingKeys: String, CodingKey {
        case end
        case start
    }

    public init(end: Int, start: Int) {
        self.end = end
        self.start = start
    }
}

public struct EverframeReportFailed: Codable, Equatable {
    public let correlationId: String
    public let reason: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case reason
        case type
    }

    public init(correlationId: String, reason: String, type: String) {
        self.correlationId = correlationId
        self.reason = reason
        self.type = type
    }
}

public struct EverframeReportRejected: Codable, Equatable {
    public let correlationId: String?
    public let reason: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case reason
        case type
    }

    public init(correlationId: String? = nil, reason: String, type: String) {
        self.correlationId = correlationId
        self.reason = reason
        self.type = type
    }
}

public struct EverframeReportRequest: Codable, Equatable {
    public let attributionToken: String?
    public let correlationId: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case attributionToken = "attribution_token"
        case correlationId = "correlation_id"
        case type
    }

    public init(attributionToken: String? = nil, correlationId: String, type: String) {
        self.attributionToken = attributionToken
        self.correlationId = correlationId
        self.type = type
    }
}

public struct EverframeReportSubmit: Codable, Equatable {
    public let annotations: [EverframeReportSubmitAnnotationItem]
    public let correlationId: String
    public let description: EverframeReportSubmitDescription
    public let includes: EverframeReportSubmitIncludes
    public let shots: [EverframeReportSubmitShot]?
    public let title: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case annotations
        case correlationId = "correlation_id"
        case description
        case includes
        case shots
        case title
        case type
    }

    public init(annotations: [EverframeReportSubmitAnnotationItem], correlationId: String, description: EverframeReportSubmitDescription, includes: EverframeReportSubmitIncludes, shots: [EverframeReportSubmitShot]? = nil, title: String, type: String) {
        self.annotations = annotations
        self.correlationId = correlationId
        self.description = description
        self.includes = includes
        self.shots = shots
        self.title = title
        self.type = type
    }
}

public enum EverframeReportSubmitAnnotationItem: Codable, Equatable {
    case stroke(EverframeReportSubmitAnnotationItemStroke)
    case arrow(EverframeReportSubmitAnnotationItemArrow)
    case blur(EverframeReportSubmitAnnotationItemBlur)

    private enum DiscKey: String, CodingKey { case kind }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: DiscKey.self)
        let kind = try c.decode(String.self, forKey: .kind)
        switch kind {
        case "stroke": self = .stroke(try EverframeReportSubmitAnnotationItemStroke(from: decoder))
        case "arrow": self = .arrow(try EverframeReportSubmitAnnotationItemArrow(from: decoder))
        case "blur": self = .blur(try EverframeReportSubmitAnnotationItemBlur(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .kind, in: c,
                debugDescription: "Unknown EverframeReportSubmitAnnotationItem kind '\(kind)'"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .stroke(let v): try v.encode(to: encoder)
        case .arrow(let v): try v.encode(to: encoder)
        case .blur(let v): try v.encode(to: encoder)
        }
    }
}

public struct EverframeReportSubmitAnnotationItemArrow: Codable, Equatable {
    public let color: String
    public let from: [Double]
    public let kind: String
    public let strokeWidth: Double
    public let to: [Double]

    public enum CodingKeys: String, CodingKey {
        case color
        case from
        case kind
        case strokeWidth
        case to
    }

    public init(color: String, from: [Double], kind: String, strokeWidth: Double, to: [Double]) {
        self.color = color
        self.from = from
        self.kind = kind
        self.strokeWidth = strokeWidth
        self.to = to
    }
}

public struct EverframeReportSubmitAnnotationItemBlur: Codable, Equatable {
    public let kind: String
    public let rect: EverframeReportSubmitAnnotationItemBlurRect

    public enum CodingKeys: String, CodingKey {
        case kind
        case rect
    }

    public init(kind: String, rect: EverframeReportSubmitAnnotationItemBlurRect) {
        self.kind = kind
        self.rect = rect
    }
}

public struct EverframeReportSubmitAnnotationItemBlurRect: Codable, Equatable {
    public let h: Double
    public let w: Double
    public let x: Double
    public let y: Double

    public enum CodingKeys: String, CodingKey {
        case h
        case w
        case x
        case y
    }

    public init(h: Double, w: Double, x: Double, y: Double) {
        self.h = h
        self.w = w
        self.x = x
        self.y = y
    }
}

public struct EverframeReportSubmitAnnotationItemStroke: Codable, Equatable {
    public let color: String
    public let kind: String
    public let points: [[Double]]
    public let strokeWidth: Double

    public enum CodingKeys: String, CodingKey {
        case color
        case kind
        case points
        case strokeWidth
    }

    public init(color: String, kind: String, points: [[Double]], strokeWidth: Double) {
        self.color = color
        self.kind = kind
        self.points = points
        self.strokeWidth = strokeWidth
    }
}

public struct EverframeReportSubmitDescription: Codable, Equatable {
    public let redactions: [EverframeReportSubmitDescriptionRedaction]
    public let text: String

    public enum CodingKeys: String, CodingKey {
        case redactions
        case text
    }

    public init(redactions: [EverframeReportSubmitDescriptionRedaction], text: String) {
        self.redactions = redactions
        self.text = text
    }
}

public struct EverframeReportSubmitDescriptionRedaction: Codable, Equatable {
    public let end: Int
    public let start: Int

    public enum CodingKeys: String, CodingKey {
        case end
        case start
    }

    public init(end: Int, start: Int) {
        self.end = end
        self.start = start
    }
}

public struct EverframeReportSubmitIncludes: Codable, Equatable {
    public let logs: Bool
    public let metadata: Bool
    public let network: Bool
    public let screenshot: Bool
    public let uiTree: Bool

    public enum CodingKeys: String, CodingKey {
        case logs
        case metadata
        case network
        case screenshot
        case uiTree
    }

    public init(logs: Bool, metadata: Bool, network: Bool, screenshot: Bool, uiTree: Bool) {
        self.logs = logs
        self.metadata = metadata
        self.network = network
        self.screenshot = screenshot
        self.uiTree = uiTree
    }
}

public struct EverframeReportSubmitShot: Codable, Equatable {
    public let annotations: [EverframeReportSubmitShotAnnotationItem]
    public let shotId: String

    public enum CodingKeys: String, CodingKey {
        case annotations
        case shotId = "shot_id"
    }

    public init(annotations: [EverframeReportSubmitShotAnnotationItem], shotId: String) {
        self.annotations = annotations
        self.shotId = shotId
    }
}

public enum EverframeReportSubmitShotAnnotationItem: Codable, Equatable {
    case stroke(EverframeReportSubmitShotAnnotationItemStroke)
    case arrow(EverframeReportSubmitShotAnnotationItemArrow)
    case blur(EverframeReportSubmitShotAnnotationItemBlur)

    private enum DiscKey: String, CodingKey { case kind }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: DiscKey.self)
        let kind = try c.decode(String.self, forKey: .kind)
        switch kind {
        case "stroke": self = .stroke(try EverframeReportSubmitShotAnnotationItemStroke(from: decoder))
        case "arrow": self = .arrow(try EverframeReportSubmitShotAnnotationItemArrow(from: decoder))
        case "blur": self = .blur(try EverframeReportSubmitShotAnnotationItemBlur(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .kind, in: c,
                debugDescription: "Unknown EverframeReportSubmitShotAnnotationItem kind '\(kind)'"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .stroke(let v): try v.encode(to: encoder)
        case .arrow(let v): try v.encode(to: encoder)
        case .blur(let v): try v.encode(to: encoder)
        }
    }
}

public struct EverframeReportSubmitShotAnnotationItemArrow: Codable, Equatable {
    public let color: String
    public let from: [Double]
    public let kind: String
    public let strokeWidth: Double
    public let to: [Double]

    public enum CodingKeys: String, CodingKey {
        case color
        case from
        case kind
        case strokeWidth
        case to
    }

    public init(color: String, from: [Double], kind: String, strokeWidth: Double, to: [Double]) {
        self.color = color
        self.from = from
        self.kind = kind
        self.strokeWidth = strokeWidth
        self.to = to
    }
}

public struct EverframeReportSubmitShotAnnotationItemBlur: Codable, Equatable {
    public let kind: String
    public let rect: EverframeReportSubmitShotAnnotationItemBlurRect

    public enum CodingKeys: String, CodingKey {
        case kind
        case rect
    }

    public init(kind: String, rect: EverframeReportSubmitShotAnnotationItemBlurRect) {
        self.kind = kind
        self.rect = rect
    }
}

public struct EverframeReportSubmitShotAnnotationItemBlurRect: Codable, Equatable {
    public let h: Double
    public let w: Double
    public let x: Double
    public let y: Double

    public enum CodingKeys: String, CodingKey {
        case h
        case w
        case x
        case y
    }

    public init(h: Double, w: Double, x: Double, y: Double) {
        self.h = h
        self.w = w
        self.x = x
        self.y = y
    }
}

public struct EverframeReportSubmitShotAnnotationItemStroke: Codable, Equatable {
    public let color: String
    public let kind: String
    public let points: [[Double]]
    public let strokeWidth: Double

    public enum CodingKeys: String, CodingKey {
        case color
        case kind
        case points
        case strokeWidth
    }

    public init(color: String, kind: String, points: [[Double]], strokeWidth: Double) {
        self.color = color
        self.kind = kind
        self.points = points
        self.strokeWidth = strokeWidth
    }
}

public struct EverframeShotAssembled: Codable, Equatable {
    public let correlationId: String
    public let height: Int
    public let mime: String
    public let shotId: String
    public let size: Int
    public let type: String
    public let width: Int

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case height
        case mime
        case shotId = "shot_id"
        case size
        case type
        case width
    }

    public init(correlationId: String, height: Int, mime: String, shotId: String, size: Int, type: String, width: Int) {
        self.correlationId = correlationId
        self.height = height
        self.mime = mime
        self.shotId = shotId
        self.size = size
        self.type = type
        self.width = width
    }
}

public struct EverframeShotBinary: Codable, Equatable {
    public let correlationId: String
    public let shotId: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case shotId = "shot_id"
        case type
    }

    public init(correlationId: String, shotId: String, type: String) {
        self.correlationId = correlationId
        self.shotId = shotId
        self.type = type
    }
}

public struct EverframeShotFailed: Codable, Equatable {
    public let correlationId: String
    public let reason: String
    public let shotId: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case reason
        case shotId = "shot_id"
        case type
    }

    public init(correlationId: String, reason: String, shotId: String, type: String) {
        self.correlationId = correlationId
        self.reason = reason
        self.shotId = shotId
        self.type = type
    }
}

public struct EverframeShotRequest: Codable, Equatable {
    public let correlationId: String
    public let rect: EverframeShotRequestRect?
    public let shotId: String
    public let type: String

    public enum CodingKeys: String, CodingKey {
        case correlationId = "correlation_id"
        case rect
        case shotId = "shot_id"
        case type
    }

    public init(correlationId: String, rect: EverframeShotRequestRect? = nil, shotId: String, type: String) {
        self.correlationId = correlationId
        self.rect = rect
        self.shotId = shotId
        self.type = type
    }
}

public struct EverframeShotRequestRect: Codable, Equatable {
    public let h: Double
    public let w: Double
    public let x: Double
    public let y: Double

    public enum CodingKeys: String, CodingKey {
        case h
        case w
        case x
        case y
    }

    public init(h: Double, w: Double, x: Double, y: Double) {
        self.h = h
        self.w = w
        self.x = x
        self.y = y
    }
}

public enum EverframeRelayMessage: Codable, Equatable {
    case attachChallenge(EverframeAttachChallenge)
    case attachChallengeCleared(EverframeAttachChallengeCleared)
    case companionName(EverframeCompanionName)
    case pairBonded(EverframePairBonded)
    case pairCreated(EverframePairCreated)
    case pairExpired(EverframePairExpired)
    case phoneDisconnected(EverframePhoneDisconnected)
    case previewFrame(EverframePreviewFrame)
    case previewStart(EverframePreviewStart)
    case previewStop(EverframePreviewStop)
    case reportAssembled(EverframeReportAssembled)
    case reportCancelled(EverframeReportCancelled)
    case reportCompleted(EverframeReportCompleted)
    case reportDraftUpdate(EverframeReportDraftUpdate)
    case reportFailed(EverframeReportFailed)
    case reportRejected(EverframeReportRejected)
    case reportRequest(EverframeReportRequest)
    case reportSubmit(EverframeReportSubmit)
    case shotAssembled(EverframeShotAssembled)
    case shotBinary(EverframeShotBinary)
    case shotFailed(EverframeShotFailed)
    case shotRequest(EverframeShotRequest)

    private enum DiscKey: String, CodingKey { case type }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: DiscKey.self)
        let type = try c.decode(String.self, forKey: .type)
        switch type {
        case "attach.challenge": self = .attachChallenge(try EverframeAttachChallenge(from: decoder))
        case "attach.challenge.cleared": self = .attachChallengeCleared(try EverframeAttachChallengeCleared(from: decoder))
        case "companion.name": self = .companionName(try EverframeCompanionName(from: decoder))
        case "pair.bonded": self = .pairBonded(try EverframePairBonded(from: decoder))
        case "pair.created": self = .pairCreated(try EverframePairCreated(from: decoder))
        case "pair.expired": self = .pairExpired(try EverframePairExpired(from: decoder))
        case "phone.disconnected": self = .phoneDisconnected(try EverframePhoneDisconnected(from: decoder))
        case "preview.frame": self = .previewFrame(try EverframePreviewFrame(from: decoder))
        case "preview.start": self = .previewStart(try EverframePreviewStart(from: decoder))
        case "preview.stop": self = .previewStop(try EverframePreviewStop(from: decoder))
        case "report.assembled": self = .reportAssembled(try EverframeReportAssembled(from: decoder))
        case "report.cancelled": self = .reportCancelled(try EverframeReportCancelled(from: decoder))
        case "report.completed": self = .reportCompleted(try EverframeReportCompleted(from: decoder))
        case "report.draft.update": self = .reportDraftUpdate(try EverframeReportDraftUpdate(from: decoder))
        case "report.failed": self = .reportFailed(try EverframeReportFailed(from: decoder))
        case "report.rejected": self = .reportRejected(try EverframeReportRejected(from: decoder))
        case "report.request": self = .reportRequest(try EverframeReportRequest(from: decoder))
        case "report.submit": self = .reportSubmit(try EverframeReportSubmit(from: decoder))
        case "shot.assembled": self = .shotAssembled(try EverframeShotAssembled(from: decoder))
        case "shot.binary": self = .shotBinary(try EverframeShotBinary(from: decoder))
        case "shot.failed": self = .shotFailed(try EverframeShotFailed(from: decoder))
        case "shot.request": self = .shotRequest(try EverframeShotRequest(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .type, in: c,
                debugDescription: "Unknown EverframeRelayMessage type '\(type)'"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .attachChallenge(let v): try v.encode(to: encoder)
        case .attachChallengeCleared(let v): try v.encode(to: encoder)
        case .companionName(let v): try v.encode(to: encoder)
        case .pairBonded(let v): try v.encode(to: encoder)
        case .pairCreated(let v): try v.encode(to: encoder)
        case .pairExpired(let v): try v.encode(to: encoder)
        case .phoneDisconnected(let v): try v.encode(to: encoder)
        case .previewFrame(let v): try v.encode(to: encoder)
        case .previewStart(let v): try v.encode(to: encoder)
        case .previewStop(let v): try v.encode(to: encoder)
        case .reportAssembled(let v): try v.encode(to: encoder)
        case .reportCancelled(let v): try v.encode(to: encoder)
        case .reportCompleted(let v): try v.encode(to: encoder)
        case .reportDraftUpdate(let v): try v.encode(to: encoder)
        case .reportFailed(let v): try v.encode(to: encoder)
        case .reportRejected(let v): try v.encode(to: encoder)
        case .reportRequest(let v): try v.encode(to: encoder)
        case .reportSubmit(let v): try v.encode(to: encoder)
        case .shotAssembled(let v): try v.encode(to: encoder)
        case .shotBinary(let v): try v.encode(to: encoder)
        case .shotFailed(let v): try v.encode(to: encoder)
        case .shotRequest(let v): try v.encode(to: encoder)
        }
    }
}
