// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 ScriptX
// AUTOGENERATED by packages/protocol/scripts/codegen-swift.sh — DO NOT EDIT.
// To regenerate: pnpm -w codegen
// CI gate: pnpm -w codegen && git diff --exit-code packages/sdk-ios/Sources/TraceItXProtocol/

// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse the JSON, add this file to your project and do:
//
//   let reportEnvelope = try ReportEnvelope(json)

import Foundation

// MARK: - ReportEnvelope
public struct ReportEnvelope: Codable {
    public let attachments: [Attachment]
    public let captureControl: CaptureControl
    public let captures: Captures
    public let context: Context
    public let payload: Payload
    public let protocolVersion: ProtocolVersion
    public let reporter: Reporter
    public let reportID: String
    public let sdk: SDK
    public let sessionID: String?
    public let source: ReportEnvelopeSource?
    public let submittedAt: Date

    public enum CodingKeys: String, CodingKey {
        case attachments, captureControl, captures, context, payload, protocolVersion, reporter
        case reportID = "reportId"
        case sdk
        case sessionID = "sessionId"
        case source, submittedAt
    }

    public init(attachments: [Attachment], captureControl: CaptureControl, captures: Captures, context: Context, payload: Payload, protocolVersion: ProtocolVersion, reporter: Reporter, reportID: String, sdk: SDK, sessionID: String?, source: ReportEnvelopeSource?, submittedAt: Date) {
        self.attachments = attachments
        self.captureControl = captureControl
        self.captures = captures
        self.context = context
        self.payload = payload
        self.protocolVersion = protocolVersion
        self.reporter = reporter
        self.reportID = reportID
        self.sdk = sdk
        self.sessionID = sessionID
        self.source = source
        self.submittedAt = submittedAt
    }
}

// MARK: ReportEnvelope convenience initializers and mutators

public extension ReportEnvelope {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(ReportEnvelope.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        attachments: [Attachment]? = nil,
        captureControl: CaptureControl? = nil,
        captures: Captures? = nil,
        context: Context? = nil,
        payload: Payload? = nil,
        protocolVersion: ProtocolVersion? = nil,
        reporter: Reporter? = nil,
        reportID: String? = nil,
        sdk: SDK? = nil,
        sessionID: String?? = nil,
        source: ReportEnvelopeSource?? = nil,
        submittedAt: Date? = nil
    ) -> ReportEnvelope {
        return ReportEnvelope(
            attachments: attachments ?? self.attachments,
            captureControl: captureControl ?? self.captureControl,
            captures: captures ?? self.captures,
            context: context ?? self.context,
            payload: payload ?? self.payload,
            protocolVersion: protocolVersion ?? self.protocolVersion,
            reporter: reporter ?? self.reporter,
            reportID: reportID ?? self.reportID,
            sdk: sdk ?? self.sdk,
            sessionID: sessionID ?? self.sessionID,
            source: source ?? self.source,
            submittedAt: submittedAt ?? self.submittedAt
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Attachment
public struct Attachment: Codable {
    public let byteLength: Double
    public let contentType: String
    public let durationMS: Double?
    public let format: Format?
    public let height: Double?
    public let kind: AttachmentKind
    public let partName: String
    public let replayStartEpochMS: Double?
    public let sha256: String
    public let width: Double?

    public enum CodingKeys: String, CodingKey {
        case byteLength, contentType
        case durationMS = "durationMs"
        case format, height, kind, partName
        case replayStartEpochMS = "replayStartEpochMs"
        case sha256, width
    }

    public init(byteLength: Double, contentType: String, durationMS: Double?, format: Format?, height: Double?, kind: AttachmentKind, partName: String, replayStartEpochMS: Double?, sha256: String, width: Double?) {
        self.byteLength = byteLength
        self.contentType = contentType
        self.durationMS = durationMS
        self.format = format
        self.height = height
        self.kind = kind
        self.partName = partName
        self.replayStartEpochMS = replayStartEpochMS
        self.sha256 = sha256
        self.width = width
    }
}

// MARK: Attachment convenience initializers and mutators

public extension Attachment {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Attachment.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        byteLength: Double? = nil,
        contentType: String? = nil,
        durationMS: Double?? = nil,
        format: Format?? = nil,
        height: Double?? = nil,
        kind: AttachmentKind? = nil,
        partName: String? = nil,
        replayStartEpochMS: Double?? = nil,
        sha256: String? = nil,
        width: Double?? = nil
    ) -> Attachment {
        return Attachment(
            byteLength: byteLength ?? self.byteLength,
            contentType: contentType ?? self.contentType,
            durationMS: durationMS ?? self.durationMS,
            format: format ?? self.format,
            height: height ?? self.height,
            kind: kind ?? self.kind,
            partName: partName ?? self.partName,
            replayStartEpochMS: replayStartEpochMS ?? self.replayStartEpochMS,
            sha256: sha256 ?? self.sha256,
            width: width ?? self.width
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum Format: String, Codable {
    case rrweb = "rrweb"
    case traceitxVideoV1 = "traceitx-video-v1"
    case traceitxVtreeV1 = "traceitx-vtree-v1"
}

public enum AttachmentKind: String, Codable {
    case annotatedScreenshot = "annotated-screenshot"
    case audio = "audio"
    case other = "other"
    case screenshot = "screenshot"
    case sessionReplay = "session-replay"
    case video = "video"
}

// MARK: - CaptureControl
public struct CaptureControl: Codable {
    public let degradedReason: String?
    public let excluded, included: [String]

    public init(degradedReason: String?, excluded: [String], included: [String]) {
        self.degradedReason = degradedReason
        self.excluded = excluded
        self.included = included
    }
}

// MARK: CaptureControl convenience initializers and mutators

public extension CaptureControl {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(CaptureControl.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        degradedReason: String?? = nil,
        excluded: [String]? = nil,
        included: [String]? = nil
    ) -> CaptureControl {
        return CaptureControl(
            degradedReason: degradedReason ?? self.degradedReason,
            excluded: excluded ?? self.excluded,
            included: included ?? self.included
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Captures
public struct Captures: Codable {
    public let breadcrumbs: Bool?
    public let focus, logs, network, screenshot: Bool
    public let uiTree: Bool

    public init(breadcrumbs: Bool?, focus: Bool, logs: Bool, network: Bool, screenshot: Bool, uiTree: Bool) {
        self.breadcrumbs = breadcrumbs
        self.focus = focus
        self.logs = logs
        self.network = network
        self.screenshot = screenshot
        self.uiTree = uiTree
    }
}

// MARK: Captures convenience initializers and mutators

public extension Captures {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Captures.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        breadcrumbs: Bool?? = nil,
        focus: Bool? = nil,
        logs: Bool? = nil,
        network: Bool? = nil,
        screenshot: Bool? = nil,
        uiTree: Bool? = nil
    ) -> Captures {
        return Captures(
            breadcrumbs: breadcrumbs ?? self.breadcrumbs,
            focus: focus ?? self.focus,
            logs: logs ?? self.logs,
            network: network ?? self.network,
            screenshot: screenshot ?? self.screenshot,
            uiTree: uiTree ?? self.uiTree
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Context
public struct Context: Codable {
    public let app: App
    public let device: Device
    public let route: String?

    public init(app: App, device: Device, route: String?) {
        self.app = app
        self.device = device
        self.route = route
    }
}

// MARK: Context convenience initializers and mutators

public extension Context {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Context.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        app: App? = nil,
        device: Device? = nil,
        route: String?? = nil
    ) -> Context {
        return Context(
            app: app ?? self.app,
            device: device ?? self.device,
            route: route ?? self.route
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - App
public struct App: Codable {
    public let build: String?
    public let name, version: String

    public init(build: String?, name: String, version: String) {
        self.build = build
        self.name = name
        self.version = version
    }
}

// MARK: App convenience initializers and mutators

public extension App {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(App.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        build: String?? = nil,
        name: String? = nil,
        version: String? = nil
    ) -> App {
        return App(
            build: build ?? self.build,
            name: name ?? self.name,
            version: version ?? self.version
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Device
public struct Device: Codable {
    public let locale: String
    public let model: String?
    public let os, osVersion: String
    public let pixelRatio: Double
    public let screenSize: ScreenSize
    public let timezone: String
    public let userAgent: String?

    public init(locale: String, model: String?, os: String, osVersion: String, pixelRatio: Double, screenSize: ScreenSize, timezone: String, userAgent: String?) {
        self.locale = locale
        self.model = model
        self.os = os
        self.osVersion = osVersion
        self.pixelRatio = pixelRatio
        self.screenSize = screenSize
        self.timezone = timezone
        self.userAgent = userAgent
    }
}

// MARK: Device convenience initializers and mutators

public extension Device {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Device.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        locale: String? = nil,
        model: String?? = nil,
        os: String? = nil,
        osVersion: String? = nil,
        pixelRatio: Double? = nil,
        screenSize: ScreenSize? = nil,
        timezone: String? = nil,
        userAgent: String?? = nil
    ) -> Device {
        return Device(
            locale: locale ?? self.locale,
            model: model ?? self.model,
            os: os ?? self.os,
            osVersion: osVersion ?? self.osVersion,
            pixelRatio: pixelRatio ?? self.pixelRatio,
            screenSize: screenSize ?? self.screenSize,
            timezone: timezone ?? self.timezone,
            userAgent: userAgent ?? self.userAgent
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - ScreenSize
public struct ScreenSize: Codable {
    public let height, width: Double

    public init(height: Double, width: Double) {
        self.height = height
        self.width = width
    }
}

// MARK: ScreenSize convenience initializers and mutators

public extension ScreenSize {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(ScreenSize.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        height: Double? = nil,
        width: Double? = nil
    ) -> ScreenSize {
        return ScreenSize(
            height: height ?? self.height,
            width: width ?? self.width
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Payload
public struct Payload: Codable {
    public let annotations: [JSONAny]?
    public let breadcrumbs: [Breadcrumb]?
    public let crash: Crash?
    public let extra: String?
    public let focus: Focus?
    public let logs, network: [JSONAny]?
    public let networkBodies: [NetworkBody]?
    public let redactions: [JSONAny]?
    public let resources: [Resource]?
    public let vitals: [Vital]?

    public init(annotations: [JSONAny]?, breadcrumbs: [Breadcrumb]?, crash: Crash?, extra: String?, focus: Focus?, logs: [JSONAny]?, network: [JSONAny]?, networkBodies: [NetworkBody]?, redactions: [JSONAny]?, resources: [Resource]?, vitals: [Vital]?) {
        self.annotations = annotations
        self.breadcrumbs = breadcrumbs
        self.crash = crash
        self.extra = extra
        self.focus = focus
        self.logs = logs
        self.network = network
        self.networkBodies = networkBodies
        self.redactions = redactions
        self.resources = resources
        self.vitals = vitals
    }
}

// MARK: Payload convenience initializers and mutators

public extension Payload {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Payload.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        annotations: [JSONAny]?? = nil,
        breadcrumbs: [Breadcrumb]?? = nil,
        crash: Crash?? = nil,
        extra: String?? = nil,
        focus: Focus?? = nil,
        logs: [JSONAny]?? = nil,
        network: [JSONAny]?? = nil,
        networkBodies: [NetworkBody]?? = nil,
        redactions: [JSONAny]?? = nil,
        resources: [Resource]?? = nil,
        vitals: [Vital]?? = nil
    ) -> Payload {
        return Payload(
            annotations: annotations ?? self.annotations,
            breadcrumbs: breadcrumbs ?? self.breadcrumbs,
            crash: crash ?? self.crash,
            extra: extra ?? self.extra,
            focus: focus ?? self.focus,
            logs: logs ?? self.logs,
            network: network ?? self.network,
            networkBodies: networkBodies ?? self.networkBodies,
            redactions: redactions ?? self.redactions,
            resources: resources ?? self.resources,
            vitals: vitals ?? self.vitals
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Breadcrumb
public struct Breadcrumb: Codable {
    public let data: [String: JSONAny]?
    public let kind: BreadcrumbKind
    public let level: Level?
    public let message: String
    public let seq: Int
    public let t: Double
    public let truncated: Bool?

    public init(data: [String: JSONAny]?, kind: BreadcrumbKind, level: Level?, message: String, seq: Int, t: Double, truncated: Bool?) {
        self.data = data
        self.kind = kind
        self.level = level
        self.message = message
        self.seq = seq
        self.t = t
        self.truncated = truncated
    }
}

// MARK: Breadcrumb convenience initializers and mutators

public extension Breadcrumb {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Breadcrumb.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        data: [String: JSONAny]?? = nil,
        kind: BreadcrumbKind? = nil,
        level: Level?? = nil,
        message: String? = nil,
        seq: Int? = nil,
        t: Double? = nil,
        truncated: Bool?? = nil
    ) -> Breadcrumb {
        return Breadcrumb(
            data: data ?? self.data,
            kind: kind ?? self.kind,
            level: level ?? self.level,
            message: message ?? self.message,
            seq: seq ?? self.seq,
            t: t ?? self.t,
            truncated: truncated ?? self.truncated
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum BreadcrumbKind: String, Codable {
    case console = "console"
    case custom = "custom"
    case error = "error"
    case lifecycle = "lifecycle"
    case navigation = "navigation"
    case network = "network"
    case tap = "tap"
}

public enum Level: String, Codable {
    case debug = "debug"
    case error = "error"
    case info = "info"
    case warn = "warn"
}

// MARK: - Crash
public struct Crash: Codable {
    public let causeChain: CrashCauseChain?
    public let details: CrashDetails?
    public let exceptionType: String
    public let fatal: Bool?
    public let fingerprint: String
    public let frames: [Frame]
    public let handled: Bool
    public let jsBundle: JSBundle?
    public let jvm: JVMCrashMetadata?
    public let mechanism: String
    public let message: String
    public let occurredAt: Date
    public let threadName: String?

    public init(causeChain: CrashCauseChain?, details: CrashDetails?, exceptionType: String, fatal: Bool?, fingerprint: String, frames: [Frame], handled: Bool, jsBundle: JSBundle?, jvm: JVMCrashMetadata?, mechanism: String, message: String, occurredAt: Date, threadName: String?) {
        self.causeChain = causeChain
        self.details = details
        self.exceptionType = exceptionType
        self.fatal = fatal
        self.fingerprint = fingerprint
        self.frames = frames
        self.handled = handled
        self.jsBundle = jsBundle
        self.jvm = jvm
        self.mechanism = mechanism
        self.message = message
        self.occurredAt = occurredAt
        self.threadName = threadName
    }
}

// MARK: Crash convenience initializers and mutators

public extension Crash {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Crash.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        causeChain: CrashCauseChain?? = nil,
        details: CrashDetails?? = nil,
        exceptionType: String? = nil,
        fatal: Bool?? = nil,
        fingerprint: String? = nil,
        frames: [Frame]? = nil,
        handled: Bool? = nil,
        jsBundle: JSBundle?? = nil,
        jvm: JVMCrashMetadata?? = nil,
        mechanism: String? = nil,
        message: String? = nil,
        occurredAt: Date? = nil,
        threadName: String?? = nil
    ) -> Crash {
        return Crash(
            causeChain: causeChain ?? self.causeChain,
            details: details ?? self.details,
            exceptionType: exceptionType ?? self.exceptionType,
            fatal: fatal ?? self.fatal,
            fingerprint: fingerprint ?? self.fingerprint,
            frames: frames ?? self.frames,
            handled: handled ?? self.handled,
            jsBundle: jsBundle ?? self.jsBundle,
            jvm: jvm ?? self.jvm,
            mechanism: mechanism ?? self.mechanism,
            message: message ?? self.message,
            occurredAt: occurredAt ?? self.occurredAt,
            threadName: threadName ?? self.threadName
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - CrashCauseChain
public struct CrashCauseChain: Codable {
    public let causes: [CrashCause]
    public let truncated: Bool

    public init(causes: [CrashCause], truncated: Bool) {
        self.causes = causes
        self.truncated = truncated
    }
}

// MARK: CrashCauseChain convenience initializers and mutators

public extension CrashCauseChain {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(CrashCauseChain.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        causes: [CrashCause]? = nil,
        truncated: Bool? = nil
    ) -> CrashCauseChain {
        return CrashCauseChain(
            causes: causes ?? self.causes,
            truncated: truncated ?? self.truncated
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - CrashCause
public struct CrashCause: Codable {
    public let exceptionType: String
    public let frames: [CrashCauseFrame]
    public let framesTruncated: Bool
    public let message: String

    public init(exceptionType: String, frames: [CrashCauseFrame], framesTruncated: Bool, message: String) {
        self.exceptionType = exceptionType
        self.frames = frames
        self.framesTruncated = framesTruncated
        self.message = message
    }
}

// MARK: CrashCause convenience initializers and mutators

public extension CrashCause {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(CrashCause.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        exceptionType: String? = nil,
        frames: [CrashCauseFrame]? = nil,
        framesTruncated: Bool? = nil,
        message: String? = nil
    ) -> CrashCause {
        return CrashCause(
            exceptionType: exceptionType ?? self.exceptionType,
            frames: frames ?? self.frames,
            framesTruncated: framesTruncated ?? self.framesTruncated,
            message: message ?? self.message
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - CrashCauseFrame
public struct CrashCauseFrame: Codable {
    public let col: Int?
    public let file: String?
    public let function: String?
    public let line: Int?
    public let raw: String

    public init(col: Int?, file: String?, function: String?, line: Int?, raw: String) {
        self.col = col
        self.file = file
        self.function = function
        self.line = line
        self.raw = raw
    }
}

// MARK: CrashCauseFrame convenience initializers and mutators

public extension CrashCauseFrame {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(CrashCauseFrame.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        col: Int?? = nil,
        file: String?? = nil,
        function: String?? = nil,
        line: Int?? = nil,
        raw: String? = nil
    ) -> CrashCauseFrame {
        return CrashCauseFrame(
            col: col ?? self.col,
            file: file ?? self.file,
            function: function ?? self.function,
            line: line ?? self.line,
            raw: raw ?? self.raw
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - CrashDetails
public struct CrashDetails: Codable {
    public let context: String?
    public let metadata: [String: JSONAny]?
    public let severity: ErrorSeverity?
    public let truncated: Bool?

    public init(context: String?, metadata: [String: JSONAny]?, severity: ErrorSeverity?, truncated: Bool?) {
        self.context = context
        self.metadata = metadata
        self.severity = severity
        self.truncated = truncated
    }
}

// MARK: CrashDetails convenience initializers and mutators

public extension CrashDetails {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(CrashDetails.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        context: String?? = nil,
        metadata: [String: JSONAny]?? = nil,
        severity: ErrorSeverity?? = nil,
        truncated: Bool?? = nil
    ) -> CrashDetails {
        return CrashDetails(
            context: context ?? self.context,
            metadata: metadata ?? self.metadata,
            severity: severity ?? self.severity,
            truncated: truncated ?? self.truncated
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum ErrorSeverity: String, Codable {
    case error = "error"
    case info = "info"
    case warning = "warning"
}

// MARK: - Frame
public struct Frame: Codable {
    public let col: Int?
    public let file: String?
    public let function: String?
    public let line: Int?
    public let raw: String

    public init(col: Int?, file: String?, function: String?, line: Int?, raw: String) {
        self.col = col
        self.file = file
        self.function = function
        self.line = line
        self.raw = raw
    }
}

// MARK: Frame convenience initializers and mutators

public extension Frame {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Frame.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        col: Int?? = nil,
        file: String?? = nil,
        function: String?? = nil,
        line: Int?? = nil,
        raw: String? = nil
    ) -> Frame {
        return Frame(
            col: col ?? self.col,
            file: file ?? self.file,
            function: function ?? self.function,
            line: line ?? self.line,
            raw: raw ?? self.raw
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - JSBundle
public struct JSBundle: Codable {
    public let buildID: String
    public let bundleName: String
    public let engine: Engine
    public let platform: JSBundlePlatform

    public enum CodingKeys: String, CodingKey {
        case buildID = "buildId"
        case bundleName, engine, platform
    }

    public init(buildID: String, bundleName: String, engine: Engine, platform: JSBundlePlatform) {
        self.buildID = buildID
        self.bundleName = bundleName
        self.engine = engine
        self.platform = platform
    }
}

// MARK: JSBundle convenience initializers and mutators

public extension JSBundle {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(JSBundle.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        buildID: String? = nil,
        bundleName: String? = nil,
        engine: Engine? = nil,
        platform: JSBundlePlatform? = nil
    ) -> JSBundle {
        return JSBundle(
            buildID: buildID ?? self.buildID,
            bundleName: bundleName ?? self.bundleName,
            engine: engine ?? self.engine,
            platform: platform ?? self.platform
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum Engine: String, Codable {
    case hermes = "hermes"
}

public enum JSBundlePlatform: String, Codable {
    case android = "android"
    case ios = "ios"
}

// MARK: - JVMCrashMetadata
public struct JVMCrashMetadata: Codable {
    public let causes: [JVMCause]
    public let causesTruncated: Bool
    public let mappingID: String?

    public enum CodingKeys: String, CodingKey {
        case causes, causesTruncated
        case mappingID = "mappingId"
    }

    public init(causes: [JVMCause], causesTruncated: Bool, mappingID: String?) {
        self.causes = causes
        self.causesTruncated = causesTruncated
        self.mappingID = mappingID
    }
}

// MARK: JVMCrashMetadata convenience initializers and mutators

public extension JVMCrashMetadata {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(JVMCrashMetadata.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        causes: [JVMCause]? = nil,
        causesTruncated: Bool? = nil,
        mappingID: String?? = nil
    ) -> JVMCrashMetadata {
        return JVMCrashMetadata(
            causes: causes ?? self.causes,
            causesTruncated: causesTruncated ?? self.causesTruncated,
            mappingID: mappingID ?? self.mappingID
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - JVMCause
public struct JVMCause: Codable {
    public let exceptionType: String
    public let frames: [Frame]
    public let framesTruncated: Bool
    public let message: String

    public init(exceptionType: String, frames: [Frame], framesTruncated: Bool, message: String) {
        self.exceptionType = exceptionType
        self.frames = frames
        self.framesTruncated = framesTruncated
        self.message = message
    }
}

// MARK: JVMCause convenience initializers and mutators

public extension JVMCause {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(JVMCause.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        exceptionType: String? = nil,
        frames: [Frame]? = nil,
        framesTruncated: Bool? = nil,
        message: String? = nil
    ) -> JVMCause {
        return JVMCause(
            exceptionType: exceptionType ?? self.exceptionType,
            frames: frames ?? self.frames,
            framesTruncated: framesTruncated ?? self.framesTruncated,
            message: message ?? self.message
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Focus
public struct Focus: Codable {
    public let componentPath: String
    public let cursor: Cursor?
    public let path: [Double]
    public let source: FocusSource

    public init(componentPath: String, cursor: Cursor?, path: [Double], source: FocusSource) {
        self.componentPath = componentPath
        self.cursor = cursor
        self.path = path
        self.source = source
    }
}

// MARK: Focus convenience initializers and mutators

public extension Focus {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Focus.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        componentPath: String? = nil,
        cursor: Cursor?? = nil,
        path: [Double]? = nil,
        source: FocusSource? = nil
    ) -> Focus {
        return Focus(
            componentPath: componentPath ?? self.componentPath,
            cursor: cursor ?? self.cursor,
            path: path ?? self.path,
            source: source ?? self.source
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Cursor
public struct Cursor: Codable {
    public let x, y: Double

    public init(x: Double, y: Double) {
        self.x = x
        self.y = y
    }
}

// MARK: Cursor convenience initializers and mutators

public extension Cursor {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Cursor.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        x: Double? = nil,
        y: Double? = nil
    ) -> Cursor {
        return Cursor(
            x: x ?? self.x,
            y: y ?? self.y
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum FocusSource: String, Codable {
    case keyboard = "keyboard"
    case mouse = "mouse"
    case programmatic = "programmatic"
    case remote = "remote"
    case touch = "touch"
}

// MARK: - NetworkBody
public struct NetworkBody: Codable {
    public let ref: Double
    public let reqBody: String?
    public let reqBodyBytes: Double?
    public let reqBodySkipped: BodySkipped?
    public let reqBodyTruncated: Bool?
    public let reqHeaders: [String: String]?
    public let resBody: String?
    public let resBodyBytes: Double?
    public let resBodySkipped: BodySkipped?
    public let resBodyTruncated: Bool?
    public let resHeaders: [String: String]?
    public let t: Double

    public init(ref: Double, reqBody: String?, reqBodyBytes: Double?, reqBodySkipped: BodySkipped?, reqBodyTruncated: Bool?, reqHeaders: [String: String]?, resBody: String?, resBodyBytes: Double?, resBodySkipped: BodySkipped?, resBodyTruncated: Bool?, resHeaders: [String: String]?, t: Double) {
        self.ref = ref
        self.reqBody = reqBody
        self.reqBodyBytes = reqBodyBytes
        self.reqBodySkipped = reqBodySkipped
        self.reqBodyTruncated = reqBodyTruncated
        self.reqHeaders = reqHeaders
        self.resBody = resBody
        self.resBodyBytes = resBodyBytes
        self.resBodySkipped = resBodySkipped
        self.resBodyTruncated = resBodyTruncated
        self.resHeaders = resHeaders
        self.t = t
    }
}

// MARK: NetworkBody convenience initializers and mutators

public extension NetworkBody {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(NetworkBody.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        ref: Double? = nil,
        reqBody: String?? = nil,
        reqBodyBytes: Double?? = nil,
        reqBodySkipped: BodySkipped?? = nil,
        reqBodyTruncated: Bool?? = nil,
        reqHeaders: [String: String]?? = nil,
        resBody: String?? = nil,
        resBodyBytes: Double?? = nil,
        resBodySkipped: BodySkipped?? = nil,
        resBodyTruncated: Bool?? = nil,
        resHeaders: [String: String]?? = nil,
        t: Double? = nil
    ) -> NetworkBody {
        return NetworkBody(
            ref: ref ?? self.ref,
            reqBody: reqBody ?? self.reqBody,
            reqBodyBytes: reqBodyBytes ?? self.reqBodyBytes,
            reqBodySkipped: reqBodySkipped ?? self.reqBodySkipped,
            reqBodyTruncated: reqBodyTruncated ?? self.reqBodyTruncated,
            reqHeaders: reqHeaders ?? self.reqHeaders,
            resBody: resBody ?? self.resBody,
            resBodyBytes: resBodyBytes ?? self.resBodyBytes,
            resBodySkipped: resBodySkipped ?? self.resBodySkipped,
            resBodyTruncated: resBodyTruncated ?? self.resBodyTruncated,
            resHeaders: resHeaders ?? self.resHeaders,
            t: t ?? self.t
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum BodySkipped: String, Codable {
    case contentType = "content-type"
    case error = "error"
    case unsupported = "unsupported"
}

// MARK: - Resource
public struct Resource: Codable {
    public let cpu: Double?
    public let extras: [String: Double]?
    public let mem: Double
    public let t: Double

    public init(cpu: Double?, extras: [String: Double]?, mem: Double, t: Double) {
        self.cpu = cpu
        self.extras = extras
        self.mem = mem
        self.t = t
    }
}

// MARK: Resource convenience initializers and mutators

public extension Resource {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Resource.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        cpu: Double?? = nil,
        extras: [String: Double]?? = nil,
        mem: Double? = nil,
        t: Double? = nil
    ) -> Resource {
        return Resource(
            cpu: cpu ?? self.cpu,
            extras: extras ?? self.extras,
            mem: mem ?? self.mem,
            t: t ?? self.t
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Vital
public struct Vital: Codable {
    public let cpu: Double?
    public let extras: [String: Double]?
    public let kind: VitalKind
    public let mem: Double?
    public let t: Double
    public let data: JSONAny?
    public let playerID: String?
    public let truncated: Bool?
    public let type: TypeEnum?
    public let name: String?

    public enum CodingKeys: String, CodingKey {
        case cpu, extras, kind, mem, t, data
        case playerID = "playerId"
        case truncated, type, name
    }

    public init(cpu: Double?, extras: [String: Double]?, kind: VitalKind, mem: Double?, t: Double, data: JSONAny?, playerID: String?, truncated: Bool?, type: TypeEnum?, name: String?) {
        self.cpu = cpu
        self.extras = extras
        self.kind = kind
        self.mem = mem
        self.t = t
        self.data = data
        self.playerID = playerID
        self.truncated = truncated
        self.type = type
        self.name = name
    }
}

// MARK: Vital convenience initializers and mutators

public extension Vital {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Vital.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        cpu: Double?? = nil,
        extras: [String: Double]?? = nil,
        kind: VitalKind? = nil,
        mem: Double?? = nil,
        t: Double? = nil,
        data: JSONAny?? = nil,
        playerID: String?? = nil,
        truncated: Bool?? = nil,
        type: TypeEnum?? = nil,
        name: String?? = nil
    ) -> Vital {
        return Vital(
            cpu: cpu ?? self.cpu,
            extras: extras ?? self.extras,
            kind: kind ?? self.kind,
            mem: mem ?? self.mem,
            t: t ?? self.t,
            data: data ?? self.data,
            playerID: playerID ?? self.playerID,
            truncated: truncated ?? self.truncated,
            type: type ?? self.type,
            name: name ?? self.name
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum VitalKind: String, Codable {
    case custom = "custom"
    case player = "player"
    case sample = "sample"
}

public enum TypeEnum: String, Codable {
    case bitrateChange = "bitrate_change"
    case bufferEnd = "buffer_end"
    case bufferStart = "buffer_start"
    case drm = "drm"
    case droppedFrames = "dropped_frames"
    case error = "error"
    case pause = "pause"
    case play = "play"
    case playerAttach = "player_attach"
    case playerDetach = "player_detach"
    case qualityChange = "quality_change"
    case rateChange = "rate_change"
    case seek = "seek"
    case sourceChange = "source_change"
    case startup = "startup"
    case stats = "stats"
}

public enum ProtocolVersion: String, Codable {
    case the10 = "1.0"
}

// MARK: - Reporter
public struct Reporter: Codable {
    public let description: String
    public let title: String
    public let user: User?

    public init(description: String, title: String, user: User?) {
        self.description = description
        self.title = title
        self.user = user
    }
}

// MARK: Reporter convenience initializers and mutators

public extension Reporter {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Reporter.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        description: String? = nil,
        title: String? = nil,
        user: User?? = nil
    ) -> Reporter {
        return Reporter(
            description: description ?? self.description,
            title: title ?? self.title,
            user: user ?? self.user
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - User
public struct User: Codable {
    public let displayName, email, id: String?

    public init(displayName: String?, email: String?, id: String?) {
        self.displayName = displayName
        self.email = email
        self.id = id
    }
}

// MARK: User convenience initializers and mutators

public extension User {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(User.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        displayName: String?? = nil,
        email: String?? = nil,
        id: String?? = nil
    ) -> User {
        return User(
            displayName: displayName ?? self.displayName,
            email: email ?? self.email,
            id: id ?? self.id
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SDK
public struct SDK: Codable {
    public let formFactor: FormFactor
    public let name: Name
    /// All TV form factors enumerated from v1 (PLAT-04)
    public let platform: Platform
    public let version: String

    public init(formFactor: FormFactor, name: Name, platform: Platform, version: String) {
        self.formFactor = formFactor
        self.name = name
        self.platform = platform
        self.version = version
    }
}

// MARK: SDK convenience initializers and mutators

public extension SDK {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SDK.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        formFactor: FormFactor? = nil,
        name: Name? = nil,
        platform: Platform? = nil,
        version: String? = nil
    ) -> SDK {
        return SDK(
            formFactor: formFactor ?? self.formFactor,
            name: name ?? self.name,
            platform: platform ?? self.platform,
            version: version ?? self.version
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

public enum FormFactor: String, Codable {
    case desktop = "desktop"
    case phone = "phone"
    case tablet = "tablet"
    case tv = "tv"
}

public enum Name: String, Codable {
    case traceitxAndroid = "traceitx-android"
    case traceitxIos = "traceitx-ios"
    case traceitxReact = "traceitx-react"
    case traceitxReactNative = "traceitx-react-native"
    case traceitxWeb = "traceitx-web"
}

/// All TV form factors enumerated from v1 (PLAT-04)
public enum Platform: String, Codable {
    case android = "android"
    case androidtv = "androidtv"
    case ios = "ios"
    case tizen = "tizen"
    case tvos = "tvos"
    case web = "web"
    case webos = "webos"
}

public enum ReportEnvelopeSource: String, Codable {
    case crash = "crash"
    case error = "error"
    case manual = "manual"
}

// MARK: - Helper functions for creating encoders and decoders

func newJSONDecoder() -> JSONDecoder {
    let decoder = JSONDecoder()
    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
        decoder.dateDecodingStrategy = .iso8601
    }
    return decoder
}

func newJSONEncoder() -> JSONEncoder {
    let encoder = JSONEncoder()
    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
        encoder.dateEncodingStrategy = .iso8601
    }
    return encoder
}

// MARK: - Encode/decode helpers

public class JSONNull: Codable, Hashable {

    public static func == (lhs: JSONNull, rhs: JSONNull) -> Bool {
            return true
    }

    public var hashValue: Int {
            return 0
    }

    public init() {}

    public required init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if !container.decodeNil() {
                    throw DecodingError.typeMismatch(JSONNull.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for JSONNull"))
            }
    }

    public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encodeNil()
    }
}

class JSONCodingKey: CodingKey {
    let key: String

    required init?(intValue: Int) {
            return nil
    }

    required init?(stringValue: String) {
            key = stringValue
    }

    var intValue: Int? {
            return nil
    }

    var stringValue: String {
            return key
    }
}

public class JSONAny: Codable {

    public let value: Any

    static func decodingError(forCodingPath codingPath: [CodingKey]) -> DecodingError {
            let context = DecodingError.Context(codingPath: codingPath, debugDescription: "Cannot decode JSONAny")
            return DecodingError.typeMismatch(JSONAny.self, context)
    }

    static func encodingError(forValue value: Any, codingPath: [CodingKey]) -> EncodingError {
            let context = EncodingError.Context(codingPath: codingPath, debugDescription: "Cannot encode JSONAny")
            return EncodingError.invalidValue(value, context)
    }

    static func decode(from container: SingleValueDecodingContainer) throws -> Any {
            if let value = try? container.decode(Bool.self) {
                    return value
            }
            if let value = try? container.decode(Int64.self) {
                    return value
            }
            if let value = try? container.decode(Double.self) {
                    return value
            }
            if let value = try? container.decode(String.self) {
                    return value
            }
            if container.decodeNil() {
                    return JSONNull()
            }
            throw decodingError(forCodingPath: container.codingPath)
    }

    static func decode(from container: inout UnkeyedDecodingContainer) throws -> Any {
            if let value = try? container.decode(Bool.self) {
                    return value
            }
            if let value = try? container.decode(Int64.self) {
                    return value
            }
            if let value = try? container.decode(Double.self) {
                    return value
            }
            if let value = try? container.decode(String.self) {
                    return value
            }
            if let value = try? container.decodeNil() {
                    if value {
                            return JSONNull()
                    }
            }
            if var container = try? container.nestedUnkeyedContainer() {
                    return try decodeArray(from: &container)
            }
            if var container = try? container.nestedContainer(keyedBy: JSONCodingKey.self) {
                    return try decodeDictionary(from: &container)
            }
            throw decodingError(forCodingPath: container.codingPath)
    }

    static func decode(from container: inout KeyedDecodingContainer<JSONCodingKey>, forKey key: JSONCodingKey) throws -> Any {
            if let value = try? container.decode(Bool.self, forKey: key) {
                    return value
            }
            if let value = try? container.decode(Int64.self, forKey: key) {
                    return value
            }
            if let value = try? container.decode(Double.self, forKey: key) {
                    return value
            }
            if let value = try? container.decode(String.self, forKey: key) {
                    return value
            }
            if let value = try? container.decodeNil(forKey: key) {
                    if value {
                            return JSONNull()
                    }
            }
            if var container = try? container.nestedUnkeyedContainer(forKey: key) {
                    return try decodeArray(from: &container)
            }
            if var container = try? container.nestedContainer(keyedBy: JSONCodingKey.self, forKey: key) {
                    return try decodeDictionary(from: &container)
            }
            throw decodingError(forCodingPath: container.codingPath)
    }

    static func decodeArray(from container: inout UnkeyedDecodingContainer) throws -> [Any] {
            var arr: [Any] = []
            while !container.isAtEnd {
                    let value = try decode(from: &container)
                    arr.append(value)
            }
            return arr
    }

    static func decodeDictionary(from container: inout KeyedDecodingContainer<JSONCodingKey>) throws -> [String: Any] {
            var dict = [String: Any]()
            for key in container.allKeys {
                    let value = try decode(from: &container, forKey: key)
                    dict[key.stringValue] = value
            }
            return dict
    }

    static func encode(to container: inout UnkeyedEncodingContainer, array: [Any]) throws {
            for value in array {
                    if let value = value as? Bool {
                            try container.encode(value)
                    } else if let value = value as? Int64 {
                            try container.encode(value)
                    } else if let value = value as? Double {
                            try container.encode(value)
                    } else if let value = value as? String {
                            try container.encode(value)
                    } else if value is JSONNull {
                            try container.encodeNil()
                    } else if let value = value as? [Any] {
                            var container = container.nestedUnkeyedContainer()
                            try encode(to: &container, array: value)
                    } else if let value = value as? [String: Any] {
                            var container = container.nestedContainer(keyedBy: JSONCodingKey.self)
                            try encode(to: &container, dictionary: value)
                    } else {
                            throw encodingError(forValue: value, codingPath: container.codingPath)
                    }
            }
    }

    static func encode(to container: inout KeyedEncodingContainer<JSONCodingKey>, dictionary: [String: Any]) throws {
            for (key, value) in dictionary {
                    let key = JSONCodingKey(stringValue: key)!
                    if let value = value as? Bool {
                            try container.encode(value, forKey: key)
                    } else if let value = value as? Int64 {
                            try container.encode(value, forKey: key)
                    } else if let value = value as? Double {
                            try container.encode(value, forKey: key)
                    } else if let value = value as? String {
                            try container.encode(value, forKey: key)
                    } else if value is JSONNull {
                            try container.encodeNil(forKey: key)
                    } else if let value = value as? [Any] {
                            var container = container.nestedUnkeyedContainer(forKey: key)
                            try encode(to: &container, array: value)
                    } else if let value = value as? [String: Any] {
                            var container = container.nestedContainer(keyedBy: JSONCodingKey.self, forKey: key)
                            try encode(to: &container, dictionary: value)
                    } else {
                            throw encodingError(forValue: value, codingPath: container.codingPath)
                    }
            }
    }

    static func encode(to container: inout SingleValueEncodingContainer, value: Any) throws {
            if let value = value as? Bool {
                    try container.encode(value)
            } else if let value = value as? Int64 {
                    try container.encode(value)
            } else if let value = value as? Double {
                    try container.encode(value)
            } else if let value = value as? String {
                    try container.encode(value)
            } else if value is JSONNull {
                    try container.encodeNil()
            } else {
                    throw encodingError(forValue: value, codingPath: container.codingPath)
            }
    }

    public required init(from decoder: Decoder) throws {
            if var arrayContainer = try? decoder.unkeyedContainer() {
                    self.value = try JSONAny.decodeArray(from: &arrayContainer)
            } else if var container = try? decoder.container(keyedBy: JSONCodingKey.self) {
                    self.value = try JSONAny.decodeDictionary(from: &container)
            } else {
                    let container = try decoder.singleValueContainer()
                    self.value = try JSONAny.decode(from: container)
            }
    }

    public func encode(to encoder: Encoder) throws {
            if let arr = self.value as? [Any] {
                    var container = encoder.unkeyedContainer()
                    try JSONAny.encode(to: &container, array: arr)
            } else if let dict = self.value as? [String: Any] {
                    var container = encoder.container(keyedBy: JSONCodingKey.self)
                    try JSONAny.encode(to: &container, dictionary: dict)
            } else {
                    var container = encoder.singleValueContainer()
                    try JSONAny.encode(to: &container, value: self.value)
            }
    }
}
