// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 ScriptX
// AUTOGENERATED by packages/protocol/scripts/codegen-vtree-swift.mjs — DO NOT EDIT.
// To regenerate: pnpm -w codegen
// CI gate: pnpm -w codegen && git diff --exit-code packages/sdk-ios/Sources/TraceItXProtocol/
//
// Custom emitter (not quicktype): the plain quicktype path duplicates the
// recursive VNode (Snapshot + Node) and flattens the VOp discriminated union
// into an all-optional struct — empirically proven (21-RESEARCH.md). This
// emitter resolves the recursive ref to a single VNode declaration and emits
// VOp as an enum with associated values. See header of codegen-vtree-swift.mjs.

import Foundation

public struct EverframeVAsset: Codable, Equatable {
    public let b64: String
    public let h: Double
    public let mime: String
    public let w: Double

    public enum CodingKeys: String, CodingKey {
        case b64
        case h
        case mime
        case w
    }

    public init(b64: String, h: Double, mime: String, w: Double) {
        self.b64 = b64
        self.h = h
        self.mime = mime
        self.w = w
    }
}

public struct EverframeVFrame: Codable, Equatable {
    public let ops: [EverframeVOp]
    public let timestamp: Double

    public enum CodingKeys: String, CodingKey {
        case ops
        case timestamp
    }

    public init(ops: [EverframeVOp], timestamp: Double) {
        self.ops = ops
        self.timestamp = timestamp
    }
}

public struct EverframeVNode: Codable, Equatable {
    public let alpha: Double?
    public let bg: String?
    public let borderColor: String?
    public let borderWidth: Double?
    public let children: [EverframeVNode]
    public let cornerRadius: Double?
    public let fontSize: Double?
    public let fontWeight: Int?
    public let frame: EverframeVRect
    public let id: String
    public let imageRef: String?
    /// INVARIANT (producer-enforced, NOT type-enforced): when `masked == true`
    /// the node MUST carry NO `text` and NO image payload (the screenshot-blackout
    /// PII parity guarantee). The dashboard player (Phase 25) defensively ignores
    /// text on masked nodes. This cannot be checked by the type system or JSON
    /// Schema — z.toJSONSchema drops the Zod .refine that enforces it.
    public let masked: Bool?
    public let role: String
    public let text: String?
    public let textAlign: String?
    public let textColor: String?

    public enum CodingKeys: String, CodingKey {
        case alpha
        case bg
        case borderColor
        case borderWidth
        case children
        case cornerRadius
        case fontSize
        case fontWeight
        case frame
        case id
        case imageRef
        case masked
        case role
        case text
        case textAlign
        case textColor
    }

    public init(alpha: Double? = nil, bg: String? = nil, borderColor: String? = nil, borderWidth: Double? = nil, children: [EverframeVNode], cornerRadius: Double? = nil, fontSize: Double? = nil, fontWeight: Int? = nil, frame: EverframeVRect, id: String, imageRef: String? = nil, masked: Bool? = nil, role: String, text: String? = nil, textAlign: String? = nil, textColor: String? = nil) {
        self.alpha = alpha
        self.bg = bg
        self.borderColor = borderColor
        self.borderWidth = borderWidth
        self.children = children
        self.cornerRadius = cornerRadius
        self.fontSize = fontSize
        self.fontWeight = fontWeight
        self.frame = frame
        self.id = id
        self.imageRef = imageRef
        self.masked = masked
        self.role = role
        self.text = text
        self.textAlign = textAlign
        self.textColor = textColor
    }
}

public enum EverframeVOp: Codable, Equatable {
    case add(EverframeVOpAdd)
    case remove(EverframeVOpRemove)
    case set(EverframeVOpSet)

    private enum DiscKey: String, CodingKey { case op }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: DiscKey.self)
        let op = try c.decode(String.self, forKey: .op)
        switch op {
        case "add": self = .add(try EverframeVOpAdd(from: decoder))
        case "remove": self = .remove(try EverframeVOpRemove(from: decoder))
        case "set": self = .set(try EverframeVOpSet(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .op, in: c,
                debugDescription: "Unknown EverframeVOp op '\(op)'"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .add(let v): try v.encode(to: encoder)
        case .remove(let v): try v.encode(to: encoder)
        case .set(let v): try v.encode(to: encoder)
        }
    }
}

public struct EverframeVOpAdd: Codable, Equatable {
    public let index: Int
    public let node: EverframeVNode
    public let op: String
    public let parent: String

    public enum CodingKeys: String, CodingKey {
        case index
        case node
        case op
        case parent
    }

    public init(index: Int, node: EverframeVNode, op: String, parent: String) {
        self.index = index
        self.node = node
        self.op = op
        self.parent = parent
    }
}

public struct EverframeVOpRemove: Codable, Equatable {
    public let id: String
    public let op: String

    public enum CodingKeys: String, CodingKey {
        case id
        case op
    }

    public init(id: String, op: String) {
        self.id = id
        self.op = op
    }
}

public struct EverframeVOpSet: Codable, Equatable {
    public let alpha: Double?
    public let bg: String?
    public let borderColor: String?
    public let borderWidth: Double?
    public let cornerRadius: Double?
    public let fontSize: Double?
    public let fontWeight: Int?
    public let frame: EverframeVRect?
    public let id: String
    public let imageRef: String?
    public let op: String
    public let text: String?
    public let textAlign: String?
    public let textColor: String?

    public enum CodingKeys: String, CodingKey {
        case alpha
        case bg
        case borderColor
        case borderWidth
        case cornerRadius
        case fontSize
        case fontWeight
        case frame
        case id
        case imageRef
        case op
        case text
        case textAlign
        case textColor
    }

    public init(alpha: Double? = nil, bg: String? = nil, borderColor: String? = nil, borderWidth: Double? = nil, cornerRadius: Double? = nil, fontSize: Double? = nil, fontWeight: Int? = nil, frame: EverframeVRect? = nil, id: String, imageRef: String? = nil, op: String, text: String? = nil, textAlign: String? = nil, textColor: String? = nil) {
        self.alpha = alpha
        self.bg = bg
        self.borderColor = borderColor
        self.borderWidth = borderWidth
        self.cornerRadius = cornerRadius
        self.fontSize = fontSize
        self.fontWeight = fontWeight
        self.frame = frame
        self.id = id
        self.imageRef = imageRef
        self.op = op
        self.text = text
        self.textAlign = textAlign
        self.textColor = textColor
    }
}

public struct EverframeVRect: Codable, Equatable {
    public let h: Double
    public let w: Double
    public let x: Double
    public let y: Double

    public enum CodingKeys: String, CodingKey {
        case h
        case w
        case x
        case y
    }

    public init(h: Double, w: Double, x: Double, y: Double) {
        self.h = h
        self.w = w
        self.x = x
        self.y = y
    }
}

public struct EverframeVTreeTimeline: Codable, Equatable {
    public let assets: [String: EverframeVAsset]?
    public let frames: [EverframeVFrame]
    public let originEpochMs: Double?
    public let version: String
    public let viewport: EverframeVTreeTimelineViewport

    public enum CodingKeys: String, CodingKey {
        case assets
        case frames
        case originEpochMs
        case version
        case viewport
    }

    public init(assets: [String: EverframeVAsset]? = nil, frames: [EverframeVFrame], originEpochMs: Double? = nil, version: String, viewport: EverframeVTreeTimelineViewport) {
        self.assets = assets
        self.frames = frames
        self.originEpochMs = originEpochMs
        self.version = version
        self.viewport = viewport
    }
}

public struct EverframeVTreeTimelineViewport: Codable, Equatable {
    public let height: Double
    public let scale: Double
    public let width: Double

    public enum CodingKeys: String, CodingKey {
        case height
        case scale
        case width
    }

    public init(height: Double, scale: Double, width: Double) {
        self.height = height
        self.scale = scale
        self.width = width
    }
}
