#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 ScriptX
#
# Materialize examples/react-web/.env.local from the optional repo-root .env.
# Idempotent. The React web sample picks up NEXT_PUBLIC_TRACEITX_KEY at
# bundle time so it doesn't fall back to the placeholder.
#
# The ingest URL is baked into @traceitx/react at its own build time
# (tsup `define`) and is not projected through Next's env layer anymore.
#
# .env.local is gitignored.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
OUT_FILE="${SCRIPT_DIR}/../.env.local"

SRC_VAR="TRACEITX_KEY_WEB"
INGEST_KEY=""

# Extract the value, stripping any inline `# comment` and surrounding
# whitespace (matches dotenv semantics used by the ingest service).
if [[ -f "${ENV_FILE}" ]]; then
    INGEST_KEY="$({ grep -E "^${SRC_VAR}=" "${ENV_FILE}" | tail -1 | cut -d= -f2- |
        sed -E 's/[[:space:]]+#.*$//; s/^[[:space:]]+//; s/[[:space:]]+$//'; } || true)"
fi

if [[ -n "${INGEST_KEY}" && ! "${INGEST_KEY}" =~ ^txx_live_.{32}$ ]]; then
    echo "error: ${SRC_VAR} in ${ENV_FILE} is missing or malformed (need 'txx_live_' + 32-char body = 41 chars)." 1>&2
    echo "       Create a 'Web' app in the dashboard (http://localhost:8787/admin/), generate its SDK key," 1>&2
    echo "       and paste it as ${SRC_VAR}=txx_live_… in the repo-root .env." 1>&2
    exit 1
fi

# --- User recognition (optional) -------------------------------------------
# Both are SERVER-ONLY — deliberately no NEXT_PUBLIC_ prefix, so Next never
# inlines them into the client bundle. The signing secret must not reach the
# browser: whoever holds it can mint a token claiming to be any of your users.
# Only app/api/traceitx-identity/route.ts reads them. Absent → that route 503s
# and the example reports anonymously, which is a supported state, not an error.
# `|| true` is required, not defensive noise: under `set -o pipefail` an absent
# var makes grep exit 1, which fails the whole assignment and — with `set -e` —
# aborts the script. These two are optional by design.
read_var() {
    [[ -f "${ENV_FILE}" ]] || return 0
    { grep -E "^$1=" "${ENV_FILE}" | tail -1 | cut -d= -f2- |
        sed -E 's/[[:space:]]+#.*$//; s/^[[:space:]]+//; s/[[:space:]]+$//'; } || true
}
IDENTITY_SECRET="$(read_var TRACEITX_IDENTITY_SECRET)"
IDENTITY_PROJECT_ID="$(read_var TRACEITX_IDENTITY_PROJECT_ID)"

# --- Playback bench streams (optional) --------------------------------------
# The /playback/* benches default to public third-party test streams (see
# app/lib/media.ts), which rot. Set any of these in the repo-root .env to
# point a bench elsewhere; this script regenerates .env.local on every dev
# run, so an override written straight into .env.local would not survive.
DEMO_HLS_URL="$(read_var NEXT_PUBLIC_DEMO_HLS_URL)"
DEMO_HLS_LIVE_URL="$(read_var NEXT_PUBLIC_DEMO_HLS_LIVE_URL)"
DEMO_DASH_URL="$(read_var NEXT_PUBLIC_DEMO_DASH_URL)"

mkdir -p "$(dirname "${OUT_FILE}")"
cat > "${OUT_FILE}" <<EOF
# GENERATED BY examples/react-web/scripts/gen-env-local.sh
# Source of truth: repo-root .env. Regenerate via 'pnpm gen-web-config'.
# Gitignored — never commit.
TRACEITX_IDENTITY_SECRET=${IDENTITY_SECRET}
TRACEITX_IDENTITY_PROJECT_ID=${IDENTITY_PROJECT_ID}
EOF
# An absent key deliberately leaves NEXT_PUBLIC_TRACEITX_KEY undefined so the
# example's credential-free `txx_live_test` fallback can build in public CI.
[[ -n "${INGEST_KEY}" ]] && echo "NEXT_PUBLIC_TRACEITX_KEY=${INGEST_KEY}" >> "${OUT_FILE}"
# Only written when set: an empty NEXT_PUBLIC_* line would override the
# code default with "", not fall through to it.
for pair in "NEXT_PUBLIC_DEMO_HLS_URL=${DEMO_HLS_URL}" \
            "NEXT_PUBLIC_DEMO_HLS_LIVE_URL=${DEMO_HLS_LIVE_URL}" \
            "NEXT_PUBLIC_DEMO_DASH_URL=${DEMO_DASH_URL}"; do
    [[ -n "${pair#*=}" ]] && echo "${pair}" >> "${OUT_FILE}"
done
echo "wrote ${OUT_FILE}"

if [[ -n "${IDENTITY_SECRET}" && -n "${IDENTITY_PROJECT_ID}" ]]; then
    echo "  user recognition: on (project ${IDENTITY_PROJECT_ID})"
else
    echo "  user recognition: off — optionally set TRACEITX_IDENTITY_SECRET + TRACEITX_IDENTITY_PROJECT_ID in ${ENV_FILE}"
fi
